/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secretary;

import java.awt.Toolkit;
import login.LogInAs;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

//for date
import java.util.Date;
import java.text.DateFormat;

//for time
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author Pro-Mahmoud Reda
 */
public class Attendence extends javax.swing.JFrame {

    /**
     * Creates new form Attendence
     */
    DefaultComboBoxModel dcm = new DefaultComboBoxModel();
    DefaultComboBoxModel dcm2 = new DefaultComboBoxModel();

    public Attendence() {
        initComponents();
        load();           //calling  //this function load the data of the level in it's listbox
        load2();          //calling  //this function load the data of the groups in it's listbox
        load3();          //calling  //this function load data of the class respect to the level
        setIcon();
    }

    private String getDate() {

        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        return dateFormat.format(date);
    }

    private String getTime() {
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        return sdf.format(cal.getTime());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(720, 260, 180, 30);

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(540, 430, 160, 30);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 415, 160, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/تسجيل حضور.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 480, 120, 50);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/تقرير الغائبين عن المجموعه1.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(740, 470, 180, 80);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/اضافه حصه.png"))); // NOI18N
        jButton4.setToolTipText("");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(590, 160, 110, 50);

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setOpaque(false);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(420, 260, 180, 30);

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        jDateChooser2.setOpaque(false);
        jPanel1.add(jDateChooser2);
        jDateChooser2.setBounds(90, 260, 190, 30);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(380, 130, 200, 30);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/تقرير الغائبين عن المستوى1.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(540, 470, 180, 80);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/تسجيل غياب1.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(30, 480, 120, 50);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/اضافه حصه للمستوى1.png"))); // NOI18N
        jButton6.setToolTipText("");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(720, 320, 190, 80);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/حذف حصه.png"))); // NOI18N
        jButton9.setToolTipText("");
        jButton9.setBorder(null);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(260, 160, 109, 50);

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/حذف حصه من مستوى1.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(410, 320, 180, 80);

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/حذف كل الحصص لمستوى1.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(100, 320, 180, 80);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/تسجيل حضور المجموعه.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(160, 530, 120, 50);

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/تسجيل حضور الكل.png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(160, 580, 120, 50);

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/تسجيل غياب لمجموعه.png"))); // NOI18N
        jButton13.setToolTipText("");
        jButton13.setBorder(null);
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(30, 530, 120, 50);

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/تسجيل غياب الكل.png"))); // NOI18N
        jButton14.setBorder(null);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(30, 580, 120, 50);

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 102, 153));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/عرض الكل.png"))); // NOI18N
        jButton17.setBorder(null);
        jButton17.setContentAreaFilled(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(580, 550, 110, 50);

        jButton18.setBackground(new java.awt.Color(255, 255, 255));
        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 102, 153));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/عرض المجموعه.png"))); // NOI18N
        jButton18.setBorder(null);
        jButton18.setContentAreaFilled(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(770, 550, 110, 50);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 450, 160, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/attendance.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-10, -50, 960, 730);

        jTabbedPane1.addTab("تسجيل حضور", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/طباعه.png"))); // NOI18N
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(440, 480, 120, 57);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "كود الطالب", "اسم الطالب", "اسم ولي الامر", "رقم ولي الامر"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(160, 160, 670, 310);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/backg.jpg"))); // NOI18N
        jPanel3.add(jLabel17);
        jLabel17.setBounds(0, 0, 950, 640);

        jTabbedPane1.addTab("الغائبين", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/طباعه.png"))); // NOI18N
        jButton15.setOpaque(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton15);
        jButton15.setBounds(440, 480, 120, 57);

        jTable3.setAutoCreateRowSorter(true);
        jTable3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "كود الطالب", "اسم الطالب", "اسم ولي الامر", "رقم ولي الامر"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jTable3.setRowHeight(25);
        jScrollPane3.setViewportView(jTable3);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(140, 160, 670, 310);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/backg.jpg"))); // NOI18N
        jPanel5.add(jLabel19);
        jLabel19.setBounds(0, 0, 950, 640);

        jTabbedPane1.addTab("الحاضرين", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "رقم الحصة", "من", "الى"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(25);
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(120, 210, 720, 270);

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox3MouseClicked(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(390, 40, 190, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/lessons.jpg"))); // NOI18N
        jPanel4.add(jLabel18);
        jLabel18.setBounds(0, 0, 950, 640);

        jTabbedPane1.addTab("الحصص", jPanel4);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel3);
        jLabel3.setBounds(100, 10, 0, 0);

        jLabel62.setBackground(new java.awt.Color(0, 102, 204));
        jLabel62.setForeground(new java.awt.Color(0, 102, 204));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/house-outline.jpg"))); // NOI18N
        jLabel62.setToolTipText("الصفحة الرئيسية");
        jLabel62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel62);
        jLabel62.setBounds(90, 30, 50, 40);

        jLabel60.setBackground(new java.awt.Color(0, 102, 204));
        jLabel60.setForeground(new java.awt.Color(0, 102, 204));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/settings.jpg"))); // NOI18N
        jLabel60.setToolTipText("الاعدادات");
        jLabel60.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel60);
        jLabel60.setBounds(10, 30, 60, 40);

        jLabel61.setBackground(new java.awt.Color(0, 102, 204));
        jLabel61.setForeground(new java.awt.Color(0, 102, 204));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/logout.jpg"))); // NOI18N
        jLabel61.setToolTipText("تسجيل الخروج");
        jLabel61.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel61MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel61);
        jLabel61.setBounds(150, 30, 60, 40);

        jButton26.setBackground(new java.awt.Color(255, 255, 255));
        jButton26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton26.setContentAreaFilled(false);
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton26);
        jButton26.setBounds(40, 110, 145, 50);

        jButton22.setBackground(new java.awt.Color(255, 255, 255));
        jButton22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton22.setContentAreaFilled(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton22);
        jButton22.setBounds(40, 190, 145, 50);

        jButton23.setBackground(new java.awt.Color(255, 255, 255));
        jButton23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton23.setContentAreaFilled(false);
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton23);
        jButton23.setBounds(40, 270, 145, 50);

        jButton25.setBackground(new java.awt.Color(255, 255, 255));
        jButton25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton25.setContentAreaFilled(false);
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton25);
        jButton25.setBounds(40, 350, 145, 55);

        jButton21.setBackground(new java.awt.Color(255, 255, 255));
        jButton21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton21.setContentAreaFilled(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton21);
        jButton21.setBounds(40, 425, 145, 50);

        jButton24.setBackground(new java.awt.Color(255, 255, 255));
        jButton24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton24.setContentAreaFilled(false);
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton24);
        jButton24.setBounds(40, 510, 145, 55);

        jButton28.setBackground(new java.awt.Color(255, 255, 255));
        jButton28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton28.setContentAreaFilled(false);
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton28);
        jButton28.setBounds(40, 590, 145, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/seee2.jpg"))); // NOI18N
        jPanel8.add(jLabel8);
        jLabel8.setBounds(0, 0, 230, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1200, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String num = jTextField2.getText();
        String id = "";
        String level_name = "";
        String group_name = "";

        if (num.equals("")) {
            JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة حصة", "...عذرا", 0);
            return;
        }
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt4 = c.prepareStatement("select * from student");
            ResultSet set4 = stmt4.executeQuery();
            while (set4.next()) {
                id = set4.getString("student_id");
            }
            if ("".equals(id)) {
                JOptionPane.showMessageDialog(this, "يجب اضافة طالب واحد على الاقل قبل اضافة حصه", "عذرا", 2);
                return;
            }
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "هناك خطا ما حدث تاكد من ان الحصة التي اخترتها تمت اضافتها", "عذرا", 2);
            System.out.println("Error" + ex.getErrorCode());
        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement s = c.prepareStatement("insert into class values(?)");
            s.setString(1, num);
            s.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "هذه الحصه قد تمت اضافتها من قبل", "عذراا", 0);
            return;
        }
        JOptionPane.showMessageDialog(null, "تم الاضافة بنجاح", "...تم", JOptionPane.PLAIN_MESSAGE);
        /*
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt2 = c.prepareStatement("select * from student");
            ResultSet set2 = stmt2.executeQuery();
            while (set2.next()) {
                id = set2.getString("student_id");
                level_name = set2.getString("student_level");
                group_name = set2.getString("student_group");
                PreparedStatement s = c.prepareStatement("insert into attendence values(?,?,?,?,?)");
                s.setString(1, num);
                s.setString(2, id);
                s.setString(3, group_name);
                s.setString(4, level_name);
                s.setString(5, "غائب");
                s.executeUpdate();

            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "هناك خطا ما حدث تاكد من ان الحصة التي اخترتها تمت اضافتها", "عذرا", 2);
            System.out.println("Error" + ex.getErrorCode());
        }
         */

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String level = jComboBox1.getSelectedItem().toString();
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt5 = c.prepareStatement("select class.num, class_level.class_num from class , class_level where class_num=? and num=class_num and class_level.level_name=?");
            stmt5.setString(1, jTextField2.getText());
            stmt5.setString(2, level);
            ResultSet set5 = stmt5.executeQuery();
            if (set5.next() == false) {
                JOptionPane.showMessageDialog(this, "يجب عليك اضافة الحصة اولا ثم تاكد من اضافة الحصة للمستوى الدراسي", "Sorry", 2);
                return;
            }
        } catch (SQLException ex1) {
            System.out.println("Error" + ex1.getErrorCode());

        }

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select *from student");

            ResultSet set = stmt.executeQuery();

            String check_num = "", num = "", group = "", level_name = "";

            check_num = jTextField1.getText();
            String check_level = jComboBox1.getSelectedItem().toString();
            String check_group = jComboBox2.getSelectedItem().toString();
            while (set.next()) {
                num = set.getString("student_id");

                if (num.equals(check_num)) {
                    level_name = set.getString("student_level");
                    group = set.getString("student_group");
                    break;
                }

            }
            if (!check_num.equals(num) && !check_num.equals("")) {

                JOptionPane.showMessageDialog(this, "يرجى التاكد من وجود كود الطالب", "تحذير", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if (!check_level.equals(level_name)) {
                JOptionPane.showMessageDialog(this, "هذا الطالب غير موجود في هذا المستوى قد يكون المستوى المطلوب" + level_name, "تحذير", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (!check_group.equals(group)) {
                JOptionPane.showMessageDialog(this, "هذا الطالب غير موجود في هذه المجموعة قد تكون المجموعة المقصوده " + group, "تحذير", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

        String num = jTextField2.getText();
        String code = jTextField1.getText();

        String group = jComboBox2.getSelectedItem().toString();

        if (num.equals("") || code.equals("") || level.equals("") || group.equals("")) {
            JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة طالب", "...عذرا", 0);
            return;
        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement s = c.prepareStatement("update attendence set mark=? where student_id=? and group_name=? and level_name=? and class_num=?");
            s.setString(1, "حاضر");
            s.setString(2, code);
            s.setString(3, group);
            s.setString(4, level);
            s.setString(5, num);
            s.executeUpdate();
            jTextField1.setText("");
            jTextField3.setText("");
            jTextField1.requestFocus();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "هناك خطا ما حدث تاكد من ان الحصة التي اخترتها تمت اضافتها", "عذرا", 2);
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String num = jTextField2.getText();
        String level_name = jComboBox1.getSelectedItem().toString();
        String group_name = jComboBox2.getSelectedItem().toString();

        try {

            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select distinct student_id from attendence where level_name=? and group_name=? and class_num=? and mark=? order by length(student_id ),student_id asc");
            stmt.setString(1, level_name);
            stmt.setString(2, group_name);
            stmt.setString(3, num);
            stmt.setString(4, "غائب");
            ResultSet set = stmt.executeQuery();

            PreparedStatement stmt2 = con.prepareStatement("select name,parent_name,parent_phone from student where student_id=? order by cast(student_id as decimal) asc");
            ResultSet set2;
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("كود الطالب");
            dm.addColumn("اسم الطالب");
            dm.addColumn("اسم ولي الامر");
            dm.addColumn("هاتف ولي الامر");

            while (set.next()) {
                String id = set.getString("student_id");
                stmt2.setString(1, id);
                set2 = stmt2.executeQuery();
                while (set2.next()) {
                    String r[] = {set.getString(1), set2.getString(1), set2.getString(2), set2.getString(3)};
                    dm.addRow(r);
                    break;
                }
            }
            jTable1.setModel(dm);
            jTabbedPane1.setSelectedComponent(jPanel3);

        } catch (SQLException ex) {

            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String level = jComboBox1.getSelectedItem().toString();
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt5 = c.prepareStatement("select class.num, class_level.class_num from class , class_level where class_num=? and num=class_num and class_level.level_name=?");
            stmt5.setString(1, jTextField2.getText());
            stmt5.setString(2, level);
            ResultSet set5 = stmt5.executeQuery();
            if (set5.next() == false) {
                JOptionPane.showMessageDialog(this, "يجب عليك اضافة الحصة اولا ثم تاكد من اضافة الحصة للمستوى الدراسي", "Sorry", 2);
                return;
            }
        } catch (SQLException ex1) {
            System.out.println("Error" + ex1.getErrorCode());

        }

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select *from student");

            ResultSet set = stmt.executeQuery();

            String check_num = "", num = "", group = "", level_name = "";

            check_num = jTextField1.getText();
            String check_level = jComboBox1.getSelectedItem().toString();
            String check_group = jComboBox2.getSelectedItem().toString();
            while (set.next()) {
                num = set.getString("student_id");

                if (num.equals(check_num)) {
                    level_name = set.getString("student_level");
                    group = set.getString("student_group");
                    break;
                }

            }
            if (!check_num.equals(num) && !check_num.equals("")) {

                JOptionPane.showMessageDialog(this, "يرجى التاكد من وجود كود الطالب", "تحذير", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if (!check_level.equals(level_name)) {
                JOptionPane.showMessageDialog(this, "هذا الطالب غير موجود في هذا المستوى قد يكون المستوى المطلوب" + level_name, "تحذير", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (!check_group.equals(group)) {
                JOptionPane.showMessageDialog(this, "هذا الطالب غير موجود في هذه المجموعة قد تكون المجموعة المقصوده " + group, "تحذير", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

        String num = jTextField2.getText();
        String code = jTextField1.getText();

        String group = jComboBox2.getSelectedItem().toString();

        if (num.equals("") || code.equals("") || level.equals("") || group.equals("")) {
            JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة طالب", "...عذرا", 0);
            return;
        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement s = c.prepareStatement("update attendence set mark=? where student_id=? and group_name=? and level_name=? and class_num=?");
            s.setString(1, "غائب");
            s.setString(2, code);
            s.setString(3, group);
            s.setString(4, level);
            s.setString(5, num);
            s.executeUpdate();
            jTextField1.setText("");
            jTextField3.setText("");
            jTextField1.requestFocus();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "هناك خطا ما حدث تاكد من ان الحصة التي اخترتها تمت اضافتها", "عذرا", 2);
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        String num = jTextField2.getText();
        String level_name = jComboBox1.getSelectedItem().toString();
        //String group_name = jComboBox2.getSelectedItem().toString();

        try {

            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select student_id from attendence where level_name=? and class_num=? and mark=? order by  length(student_id ),student_id asc");
            stmt.setString(1, level_name);
            stmt.setString(2, num);
            stmt.setString(3, "غائب");
            ResultSet set = stmt.executeQuery();

            PreparedStatement stmt2 = con.prepareStatement("select name,parent_name,parent_phone from student where student_id=?");
            ResultSet set2;
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("كود الطالب");
            dm.addColumn("اسم الطالب");
            dm.addColumn("اسم ولي الامر");
            dm.addColumn("هاتف ولي الامر");

            while (set.next()) {
                String id = set.getString("student_id");
                stmt2.setString(1, id);
                set2 = stmt2.executeQuery();
                while (set2.next()) {
                    String r[] = {set.getString(1), set2.getString(1), set2.getString(2), set2.getString(3)};
                    dm.addRow(r);
                    break;
                }
            }
            jTable1.setModel(dm);
            jTabbedPane1.setSelectedComponent(jPanel3);

        } catch (SQLException ex) {

            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        String level_name = jComboBox3.getSelectedItem().toString();

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select class_num, start_date, end_date from class_level where level_name=?");
            stmt.setString(1, level_name);
            ResultSet set = stmt.executeQuery();

            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("رقم الحصة");
            dm.addColumn("من");
            dm.addColumn("الي");

            while (set.next()) {
                String r[] = {set.getString(1), set.getString(2), set.getString(3)};
                dm.addRow(r);
            }
            jTable2.setModel(dm);

        } catch (SQLException ex) {

            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        dcm2.removeAllElements();
        String level = jComboBox1.getSelectedItem().toString();
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt2 = con.prepareStatement("select  name_group from groups_level where name_level=?");
            stmt2.setString(1, level);
            ResultSet set2 = stmt2.executeQuery();
            while (set2.next()) {
                String name2 = set2.getString("name_group");
                dcm2.addElement(name2);

            }

            jComboBox2.setModel(dcm2);
        } catch (SQLException ex) {

            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String foot = " ";
        String dt = getDate();
        String tm = getTime();

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt2 = con.prepareStatement("select * from footer");
            ResultSet set2 = stmt2.executeQuery();

            while (set2.next()) {
                foot = set2.getString("footer");
            }
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }
        MessageFormat header = new MessageFormat("غياب الحصة رقم " + jTextField2.getText() + "  " + "للصف " + jComboBox1.getSelectedItem().toString());
        MessageFormat footer = new MessageFormat(foot);
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            ////////////////for System view ////////////
            PreparedStatement stmt4 = con.prepareStatement("insert into system values(?,?,?,?)");

            stmt4.setString(1, dt);
            stmt4.setString(2, tm);
            stmt4.setString(3, "جدول الغائبين");
            stmt4.setString(4, "طباعه");
            ////////////////////////////////////////////

            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            stmt4.executeUpdate();

        } catch (PrinterException ex) {
            Logger.getLogger(Money.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(Attendence.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String num = jTextField2.getText();
        String id = "";
        String level_name = "";
        String group_name = "";

        String from = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
        String to = ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText();
        if (jTextField2.getText().equals("") || from.equals("") || from.equals("")) {
            JOptionPane.showMessageDialog(this, "يجب اضافة جميع البيانات المتعلقة بالحصه من تاريخ و رقم الحصة", "Sorry", 2);
            return;
        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt5 = c.prepareStatement("select * from class_level");
            ResultSet set5 = stmt5.executeQuery();
            while (set5.next()) {
                String level2 = set5.getString("level_name");
                String num2 = set5.getString("class_num");
                if (jTextField2.getText().equals(num2) && jComboBox1.getSelectedItem().toString().equals(level2)) {
                    JOptionPane.showMessageDialog(this, "هذه الحصة موجوده بالفعل ومضافة للمستوى", "Sorry", 2);
                    return;
                }
            }
        } catch (SQLException ex1) {
            System.out.println("Error" + ex1.getErrorCode());

        }

        try {
            String num2 = jTextField2.getText();
            String level2 = jComboBox1.getSelectedItem().toString();
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement s = c.prepareStatement("insert into class_level values(?,?,?,?)");
            s.setString(1, num2);
            s.setString(2, level2);
            s.setString(3, from);
            s.setString(4, to);
            s.executeUpdate();
        } catch (SQLException ex) {
        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt2 = c.prepareStatement("select * from student where student_level=?");
            level_name = jComboBox1.getSelectedItem().toString();
            stmt2.setString(1, level_name);
            ResultSet set2 = stmt2.executeQuery();
            while (set2.next()) {
                id = set2.getString("student_id");
                level_name = set2.getString("student_level");
                group_name = set2.getString("student_group");
                PreparedStatement s = c.prepareStatement("insert into attendence values(?,?,?,?,?)");
                s.setString(1, num);
                s.setString(2, id);
                s.setString(3, group_name);
                s.setString(4, level_name);
                s.setString(5, "غائب");
                s.executeUpdate();
            }
            JOptionPane.showMessageDialog(this, "تم اضافة الحصة للمستوى بنجاح", "تم", JOptionPane.PLAIN_MESSAGE);

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "هناك خطا ما حدث تاكد من ان الحصة التي اخترتها تمت اضافتها", "عذرا", 2);
            System.out.println("Error" + ex.getErrorCode());
        }

        String level_name2 = jComboBox3.getSelectedItem().toString();

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select class_num, start_date, end_date from class_level where level_name=?");
            stmt.setString(1, level_name2);
            ResultSet set = stmt.executeQuery();

            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("رقم الحصة");
            dm.addColumn("من");
            dm.addColumn("الي");

            while (set.next()) {
                String r[] = {set.getString(1), set.getString(2), set.getString(3)};
                dm.addRow(r);
            }
            jTable2.setModel(dm);

        } catch (SQLException ex) {

            System.out.println("Error" + ex.getErrorCode());
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String level = jComboBox1.getSelectedItem().toString();
        String class_num = jTextField2.getText();
        if (jTextField2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " فقط اكتب رقم الحصة المراد حذفها ", "...عذراا", 2);
            jTextField2.setText("");
            return;
        }
        int replay = JOptionPane.showConfirmDialog(this, "هل انت واثق من انك تريد حذف الحصة احذر سوف يتم حذف اي شيئ له علاقة بها ", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                /////////delete from the relation "class_level"\\\\\\\\\\\\\\\\\\\\\\\\
                PreparedStatement stmt = con.prepareStatement("delete from class_level where class_num=? and level_name=?");
                stmt.setString(1, class_num);
                stmt.setString(2, level);
                stmt.executeUpdate();
                /////////delete from the relation "attendence"\\\\\\\\\\\\\\\\\\\\\\\\
                PreparedStatement stmt2 = con.prepareStatement("delete from attendence where level_name=? and class_num=?");
                stmt2.setString(2, class_num);
                stmt2.setString(1, level);
                stmt2.executeUpdate();

                JOptionPane.showMessageDialog(null, "تم الحذف بنجاح", "...تم", JOptionPane.PLAIN_MESSAGE);
                jTextField2.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "الحصة غير موجوده من الاصل", "عذرا", 0);
                System.out.println("Error" + ex.getErrorCode());
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        if (jTextField2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " فقط اكتب رقم الحصة المراد حذفها ", "...عذراا", 2);
            jTextField2.setText("");
            return;
        }
        int replay = JOptionPane.showConfirmDialog(this, "هل انت واثق من انك تريد حذف الحصة احذر سوف يتم حذف اي شيئ له علاقة بها ", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                /////////delete from the relation "class_level"\\\\\\\\\\\\\\\\\\\\\\\\
                PreparedStatement stmt = con.prepareStatement("delete from class_level where class_num=?");
                stmt.setString(1, jTextField2.getText());
                stmt.executeUpdate();

                /////////delete from the relation "attendence"\\\\\\\\\\\\\\\\\\\\\\\\
                PreparedStatement stmt2 = con.prepareStatement("delete from attendence where class_num=?");
                stmt2.setString(1, jTextField2.getText());
                stmt2.executeUpdate();

                /////////delete from the table "class"\\\\\\\\\\\\\\\\\\\\\\\\
                PreparedStatement stmt3 = con.prepareStatement("delete from class where num=?");
                stmt3.setString(1, jTextField2.getText());
                stmt3.executeUpdate();

                JOptionPane.showMessageDialog(null, "تم الحذف بنجاح", "...تم", JOptionPane.PLAIN_MESSAGE);

                jTextField2.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "الحصة غير موجوده من الاصل", "عذرا", 0);
                System.out.println("Error" + ex.getErrorCode());
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "هل انت واثق من انك تريد حذف كل الحصص الخاصة بالفرقة  " + jComboBox1.getSelectedItem().toString() + " احذر سوف يتم حذف اي شيئ له علاقة بهم ", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                /////////delete from the relation "class_level"\\\\\\\\\\\\\\\\\\\\\\\\
                PreparedStatement stmt = con.prepareStatement("delete from class_level where level_name=?");
                stmt.setString(1, jComboBox1.getSelectedItem().toString());
                stmt.executeUpdate();

                /////////delete from the relation "attendence"\\\\\\\\\\\\\\\\\\\\\\\\
                PreparedStatement stmt2 = con.prepareStatement("delete from attendence where class_num=? and level_name=?");
                stmt2.setString(1, jTextField2.getText());
                stmt2.setString(2, jComboBox1.getSelectedItem().toString());
                stmt2.executeUpdate();

                JOptionPane.showMessageDialog(null, "تم الحذف بنجاح", "...تم", JOptionPane.PLAIN_MESSAGE);

                jTextField2.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "الحصة غير موجوده من الاصل", "عذرا", 0);
                System.out.println("Error" + ex.getErrorCode());
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        String level = jComboBox1.getSelectedItem().toString();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt5 = c.prepareStatement("select class.num, class_level.class_num from class , class_level where class_num=? and num=class_num and class_level.level_name=?");
                stmt5.setString(1, jTextField2.getText());
                stmt5.setString(2, level);
                ResultSet set5 = stmt5.executeQuery();
                if (set5.next() == false) {
                    JOptionPane.showMessageDialog(this, "يجب عليك اضافة الحصة اولا ثم تاكد من اضافة الحصة للمستوى الدراسي", "Sorry", 2);
                    return;
                }
            } catch (SQLException ex1) {
                System.out.println("Error" + ex1.getErrorCode());

            }

            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt = con.prepareStatement("select *from student");

                ResultSet set = stmt.executeQuery();

                String check_num = "", num = "", group = "", level_name = "";

                check_num = jTextField1.getText();
                String check_level = jComboBox1.getSelectedItem().toString();
                String check_group = jComboBox2.getSelectedItem().toString();
                while (set.next()) {
                    num = set.getString("student_id");

                    if (num.equals(check_num)) {
                        level_name = set.getString("student_level");
                        group = set.getString("student_group");
                        break;
                    }

                }
                if (!check_num.equals(num) && !check_num.equals("")) {

                    JOptionPane.showMessageDialog(this, "يرجى التاكد من وجود كود الطالب", "تحذير", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                if (!check_level.equals(level_name)) {
                    JOptionPane.showMessageDialog(this, "هذا الطالب غير موجود في هذا المستوى قد يكون المستوى المطلوب" + level_name, "تحذير", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                if (!check_group.equals(group)) {
                    JOptionPane.showMessageDialog(this, "هذا الطالب غير موجود في هذه المجموعة قد تكون المجموعة المقصوده " + group, "تحذير", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

            } catch (SQLException ex) {
                System.out.println("Error" + ex.getErrorCode());
            }

            String num = jTextField2.getText();
            String code = jTextField1.getText();

            String group = jComboBox2.getSelectedItem().toString();

            if (num.equals("") || code.equals("") || level.equals("") || group.equals("")) {
                JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة طالب", "...عذرا", 0);
                return;
            }

            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement s = c.prepareStatement("update attendence set mark=? where student_id=? and group_name=? and level_name=? and class_num=?");
                s.setString(1, "حاضر");
                s.setString(2, code);
                s.setString(3, group);
                s.setString(4, level);
                s.setString(5, num);
                s.executeUpdate();
                jTextField1.setText("");
                jTextField1.requestFocus();

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(this, "هناك خطا ما حدث تاكد من ان الحصة التي اخترتها تمت اضافتها", "عذرا", 2);
                System.out.println("Error" + ex.getErrorCode());
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        Secretary_control s = new Secretary_control();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        Settings a = new Settings();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel60MouseClicked

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String num = jTextField2.getText();
            String id = "";
            String level_name = "";
            String group_name = "";

            if (num.equals("")) {
                JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة حصة", "...عذرا", 0);
                return;
            }
            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt4 = c.prepareStatement("select * from student");
                ResultSet set4 = stmt4.executeQuery();
                while (set4.next()) {
                    id = set4.getString("student_id");
                }
                if ("".equals(id)) {
                    JOptionPane.showMessageDialog(this, "يجب اضافة طالب واحد على الاقل قبل اضافة حصه", "عذرا", 2);
                    return;
                }
            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(this, "هناك خطا ما حدث تاكد من ان الحصة التي اخترتها تمت اضافتها", "عذرا", 2);
                System.out.println("Error" + ex.getErrorCode());
            }

            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement s = c.prepareStatement("insert into class values(?)");
                s.setString(1, num);
                s.executeUpdate();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "هذه الحصه قد تمت اضافتها من قبل", "عذراا", 0);
                return;
            }

            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt2 = c.prepareStatement("select * from student");
                ResultSet set2 = stmt2.executeQuery();
                while (set2.next()) {
                    id = set2.getString("student_id");
                    level_name = set2.getString("student_level");
                    group_name = set2.getString("student_group");
                    PreparedStatement s = c.prepareStatement("insert into attendence values(?,?,?,?,?)");
                    s.setString(1, num);
                    s.setString(2, id);
                    s.setString(3, group_name);
                    s.setString(4, level_name);
                    s.setString(5, "غائب");
                    s.executeUpdate();

                }
                JOptionPane.showMessageDialog(null, "تم الاضافة بنجاح", "...تم", JOptionPane.PLAIN_MESSAGE);
            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(this, "هناك خطا ما حدث تاكد من ان الحصة التي اخترتها تمت اضافتها", "عذرا", 2);
                System.out.println("Error" + ex.getErrorCode());
            }
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jLabel61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseClicked
        int replay = JOptionPane.showConfirmDialog(null, "هل انت متاكد من انك تريد الخروج", "تاكيد", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            LogInAs a = new LogInAs();
            this.setVisible(false);
            a.setVisible(true);
        }
    }//GEN-LAST:event_jLabel61MouseClicked

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        StudnetManagement a = new StudnetManagement();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        Attendence a = new Attendence();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        Quiz a = new Quiz();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        Exams a = new Exams();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        Money a = new Money();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        Groups a = new Groups();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        report a = new report();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String num = jTextField2.getText();
        String code = jTextField1.getText();
        String level = jComboBox1.getSelectedItem().toString();
        String group = jComboBox2.getSelectedItem().toString();

        if (num.equals("") || level.equals("") || group.equals("")) {
            JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة طالب", "...عذرا", 0);
            return;
        }
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt5 = c.prepareStatement("select class.num, class_level.class_num from class , class_level where class_num=? and num=class_num and class_level.level_name=?");
            stmt5.setString(1, jTextField2.getText());
            stmt5.setString(2, level);
            ResultSet set5 = stmt5.executeQuery();
            if (set5.next() == false) {
                JOptionPane.showMessageDialog(this, "يجب عليك اضافة الحصة اولا ثم تاكد من اضافة الحصة للمستوى الدراسي", "Sorry", 2);
                return;
            }
        } catch (SQLException ex1) {
            System.out.println("Error" + ex1.getErrorCode());

        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement s = c.prepareStatement("update attendence set mark=? where group_name=? and level_name=? and class_num=?");
            s.setString(1, "حاضر");
            s.setString(2, group);
            s.setString(3, level);
            s.setString(4, num);
            s.executeUpdate();
            jTextField1.setText("");
            jTextField1.requestFocus();
            JOptionPane.showMessageDialog(null, "تم تحضير كل الطلاب الموجودين فالمجموعة " + group, "Done", -1);
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "هناك خطا ما حدث تاكد من ان الحصة التي اخترتها تمت اضافتها", "عذرا", 2);
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        String num = jTextField2.getText();

        String level = jComboBox1.getSelectedItem().toString();

        if (num.equals("") || level.equals("")) {
            JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة طالب", "...عذرا", 0);
            return;
        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt5 = c.prepareStatement("select class.num, class_level.class_num from class , class_level where class_num=? and num=class_num and class_level.level_name=?");
            stmt5.setString(1, jTextField2.getText());
            stmt5.setString(2, level);
            ResultSet set5 = stmt5.executeQuery();
            if (set5.next() == false) {
                JOptionPane.showMessageDialog(this, "يجب عليك اضافة الحصة اولا ثم تاكد من اضافة الحصة للمستوى الدراسي", "Sorry", 2);
                return;
            }
        } catch (SQLException ex1) {
            System.out.println("Error" + ex1.getErrorCode());

        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement s = c.prepareStatement("update attendence set mark=? where level_name=? and class_num=?");
            s.setString(1, "حاضر");
            s.setString(2, level);
            s.setString(3, num);
            s.executeUpdate();
            jTextField1.setText("");
            jTextField1.requestFocus();
            JOptionPane.showMessageDialog(null, "تم تحضير كل الطلاب الموجودين فالمستوى " + level, "Done", -1);
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "هناك خطا ما حدث تاكد من ان الحصة التي اخترتها تمت اضافتها", "عذرا", 2);
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        String num = jTextField2.getText();
        String level = jComboBox1.getSelectedItem().toString();
        String group = jComboBox2.getSelectedItem().toString();

        if (num.equals("") || level.equals("") || group.equals("")) {
            JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة طالب", "...عذرا", 0);
            return;
        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt5 = c.prepareStatement("select class.num, class_level.class_num from class , class_level where class_num=? and num=class_num and class_level.level_name=?");
            stmt5.setString(1, jTextField2.getText());
            stmt5.setString(2, level);
            ResultSet set5 = stmt5.executeQuery();
            if (set5.next() == false) {
                JOptionPane.showMessageDialog(this, "يجب عليك اضافة الحصة اولا ثم تاكد من اضافة الحصة للمستوى الدراسي", "Sorry", 2);
                return;
            }
        } catch (SQLException ex1) {
            System.out.println("Error" + ex1.getErrorCode());

        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt5 = c.prepareStatement("select class.num, class_level.class_num from class , class_level where class_num=? and num=class_num and class_level.level_name=?");
            stmt5.setString(1, jTextField2.getText());
            stmt5.setString(2, level);
            ResultSet set5 = stmt5.executeQuery();
            if (set5.next() == false) {
                JOptionPane.showMessageDialog(this, "يجب عليك اضافة الحصة اولا ثم تاكد من اضافة الحصة للمستوى الدراسي", "Sorry", 2);
                return;
            }
        } catch (SQLException ex1) {
            System.out.println("Error" + ex1.getErrorCode());

        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement s = c.prepareStatement("update attendence set mark=? where group_name=? and level_name=? and class_num=?");
            s.setString(1, "غائب");
            s.setString(2, group);
            s.setString(3, level);
            s.setString(4, num);
            s.executeUpdate();
            jTextField1.setText("");
            jTextField1.requestFocus();
            JOptionPane.showMessageDialog(null, "تم تغييب  كل الطلاب الموجودين فالمجموعة " + group, "Done", -1);
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "هناك خطا ما حدث تاكد من ان الحصة التي اخترتها تمت اضافتها", "عذرا", 2);
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        String num = jTextField2.getText();

        String level = jComboBox1.getSelectedItem().toString();

        if (num.equals("") || level.equals("")) {
            JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة طالب", "...عذرا", 0);
            return;
        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt5 = c.prepareStatement("select class.num, class_level.class_num from class , class_level where class_num=? and num=class_num and class_level.level_name=?");
            stmt5.setString(1, jTextField2.getText());
            stmt5.setString(2, level);
            ResultSet set5 = stmt5.executeQuery();
            if (set5.next() == false) {
                JOptionPane.showMessageDialog(this, "يجب عليك اضافة الحصة اولا ثم تاكد من اضافة الحصة للمستوى الدراسي", "Sorry", 2);
                return;
            }
        } catch (SQLException ex1) {
            System.out.println("Error" + ex1.getErrorCode());

        }

        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement s = c.prepareStatement("update attendence set mark=? where level_name=? and class_num=?");
            s.setString(1, "غائب");
            s.setString(2, level);
            s.setString(3, num);
            s.executeUpdate();
            jTextField1.setText("");
            jTextField1.requestFocus();
            JOptionPane.showMessageDialog(null, "تم تغييب كل الطلاب الموجودين فالمستوى " + level, "Done", -1);
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "هناك خطا ما حدث تاكد من ان الحصة التي اخترتها تمت اضافتها", "عذرا", 2);
            System.out.println("Error" + ex.getErrorCode());
        }


    }//GEN-LAST:event_jButton14ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        String level_name = jComboBox3.getSelectedItem().toString();

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select class_num, start_date, end_date from class_level where level_name=?");
            stmt.setString(1, level_name);
            ResultSet set = stmt.executeQuery();

            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("رقم الحصة");
            dm.addColumn("من");
            dm.addColumn("الي");

            while (set.next()) {
                String r[] = {set.getString(1), set.getString(2), set.getString(3)};
                dm.addRow(r);
            }
            jTable2.setModel(dm);

        } catch (SQLException ex) {

            System.out.println("Error" + ex.getErrorCode());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseClicked
        String level_name = jComboBox3.getSelectedItem().toString();

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select class_num, start_date, end_date from class_level where level_name=?");
            stmt.setString(1, level_name);
            ResultSet set = stmt.executeQuery();

            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("رقم الحصة");
            dm.addColumn("من");
            dm.addColumn("الي");

            while (set.next()) {
                String r[] = {set.getString(1), set.getString(2), set.getString(3)};
                dm.addRow(r);
            }
            jTable2.setModel(dm);

        } catch (SQLException ex) {

            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jComboBox3MouseClicked

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        String foot = " ";
        String dt = getDate();
        String tm = getTime();

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt2 = con.prepareStatement("select * from footer");
            ResultSet set2 = stmt2.executeQuery();

            while (set2.next()) {
                foot = set2.getString("footer");
            }
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }
        MessageFormat header = new MessageFormat(" حضور الحصة رقم" + jTextField2.getText() + "  " + "للصف " + jComboBox1.getSelectedItem().toString());
        MessageFormat footer = new MessageFormat(foot);
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            ////////////////for System view ////////////
            PreparedStatement stmt4 = con.prepareStatement("insert into system values(?,?,?,?)");

            stmt4.setString(1, dt);
            stmt4.setString(2, tm);
            stmt4.setString(3, "جدول الغائبين");
            stmt4.setString(4, "طباعه");
            ////////////////////////////////////////////

            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            stmt4.executeUpdate();

        } catch (PrinterException ex) {
            Logger.getLogger(Money.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(Attendence.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        String num = jTextField2.getText();
        String level_name = jComboBox1.getSelectedItem().toString();
        String group_name = jComboBox2.getSelectedItem().toString();
        String all_id = "", attend_id = "";

        try {

            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select distinct student_id from attendence where level_name=? and class_num=? and mark=? order by length(student_id ),student_id asc");
            stmt.setString(1, level_name);
            stmt.setString(2, num);
            stmt.setString(3, "حاضر");
            ResultSet set = stmt.executeQuery();

            PreparedStatement stmt2 = con.prepareStatement("select name,parent_name,parent_phone from student where student_id=?");
            ResultSet set2;

            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("كود الطالب");
            dm.addColumn("اسم الطالب");
            dm.addColumn("اسم ولي الامر");
            dm.addColumn("هاتف ولي الامر");

            while (set.next()) {
                String id = set.getString("student_id");

                stmt2.setString(1, id);
                set2 = stmt2.executeQuery();
                while (set2.next()) {
                    String r[] = {set.getString(1), set2.getString(1), set2.getString(2), set2.getString(3)};
                    dm.addRow(r);
                    break;
                }
            }
            jTable3.setModel(dm);
            jTabbedPane1.setSelectedComponent(jPanel5);

        } catch (SQLException ex) {

            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        String num = jTextField2.getText();
        String level_name = jComboBox1.getSelectedItem().toString();
        String group_name = jComboBox2.getSelectedItem().toString();

        try {

            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select distinct student_id from attendence where level_name=? and group_name=? and class_num=? and mark=? order by length(student_id ),student_id asc");
            stmt.setString(1, level_name);
            stmt.setString(2, group_name);
            stmt.setString(3, num);
            stmt.setString(4, "حاضر");
            ResultSet set = stmt.executeQuery();

            PreparedStatement stmt2 = con.prepareStatement("select name,parent_name,parent_phone from student where student_id=? order by cast(student_id as decimal) asc");
            ResultSet set2;
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("كود الطالب");
            dm.addColumn("اسم الطالب");
            dm.addColumn("اسم ولي الامر");
            dm.addColumn("هاتف ولي الامر");

            while (set.next()) {
                String id = set.getString("student_id");
                stmt2.setString(1, id);
                set2 = stmt2.executeQuery();
                while (set2.next()) {
                    String r[] = {set.getString(1), set2.getString(1), set2.getString(2), set2.getString(3)};
                    dm.addRow(r);
                    break;
                }
            }
            jTable3.setModel(dm);
            jTabbedPane1.setSelectedComponent(jPanel5);

        } catch (SQLException ex) {

            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select *from student where student_id=?");
            stmt.setString(1, jTextField1.getText());
            ResultSet set = stmt.executeQuery();
            String name = "";
            while (set.next()) {
                name = set.getString("name");
                break;
            }
            jTextField3.setText(name);

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select *from student where student_id=?");
            stmt.setString(1, jTextField1.getText());
            ResultSet set = stmt.executeQuery();
            String name = "";
            while (set.next()) {
                name = set.getString("name");
                break;
            }
            jTextField3.setText(name);

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendence.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendence.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendence.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendence.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendence().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void load() {
        dcm.removeAllElements();
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from level");
            ResultSet set = stmt.executeQuery();
            while (set.next()) {
                String name = set.getString("level_name");
                dcm.addElement(name);
                jComboBox1.setModel(dcm);
                jComboBox3.setModel(dcm);
            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

    }

    private void load2() {
        dcm2.removeAllElements();
        String level = "";
        try {
            level = jComboBox1.getSelectedItem().toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "يجب اضافة مستوى واحد على الاقل و مجموعة واحده على الاقل", "عذرا", 3);
        }
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt2 = con.prepareStatement("select distinct name_group from groups_level where name_level=?");
            stmt2.setString(1, level);
            ResultSet set2 = stmt2.executeQuery();
            while (set2.next()) {
                String name2 = set2.getString("name_group");
                dcm2.addElement(name2);

            }

            jComboBox2.setModel(dcm2);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }

    }

    private void load3() {

        String level_name = jComboBox3.getSelectedItem().toString();

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select class_num, start_date, end_date from class_level where level_name=?");
            stmt.setString(1, level_name);
            ResultSet set = stmt.executeQuery();

            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("رقم الحصة");
            dm.addColumn("من");
            dm.addColumn("الي");

            while (set.next()) {
                String r[] = {set.getString(1), set.getString(2), set.getString(3)};
                dm.addRow(r);
            }
            jTable2.setModel(dm);

        } catch (SQLException ex) {

            System.out.println("Error" + ex.getErrorCode());
        }

    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Photos/logo2.jpg")));
    }

}
