/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secretary;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import login.LogInAs;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

//for date
import java.util.Date;
import java.text.DateFormat;

//for time
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;

/**
 *
 * @author Pro-Mahmoud Reda
 */
public class Groups extends javax.swing.JFrame {

    //models for the two list box
    DefaultListModel dim = new DefaultListModel();    //for listbox1

    DefaultListModel dim2 = new DefaultListModel();   //for listbox2

    /**
     * Creates new form Groups
     */
    public Groups() {
        initComponents();
        load();           //calling  //this function load the data of the level in it's listbox
        load2();          //calling  //this function load the data of the groups in it's listbox
        setIcon();
    }

    private String getDate() {

        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        return dateFormat.format(date);
    }

    private String getTime() {
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        return sdf.format(cal.getTime());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jTextField11 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jTextField21 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton26 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(250, 290, 160, 30);

        jTextField12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField12);
        jTextField12.setBounds(240, 110, 160, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/اضافه مستوى.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(790, 270, 130, 50);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(530, 290, 81, 30);

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setOpaque(false);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(530, 330, 81, 30);

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setOpaque(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(530, 370, 81, 30);

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setOpaque(false);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(530, 410, 81, 30);

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setOpaque(false);
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(530, 450, 81, 30);

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setOpaque(false);
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(530, 490, 81, 30);

        jCheckBox7.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setOpaque(false);
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox7);
        jCheckBox7.setBounds(530, 530, 81, 23);

        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11);
        jTextField11.setBounds(250, 330, 160, 30);

        jTextField13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField13);
        jTextField13.setBounds(250, 370, 160, 30);

        jTextField14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField14);
        jTextField14.setBounds(250, 410, 160, 30);

        jTextField15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField15);
        jTextField15.setBounds(250, 450, 160, 30);

        jTextField16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField16);
        jTextField16.setBounds(250, 490, 160, 30);

        jTextField17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField17);
        jTextField17.setBounds(250, 530, 160, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/اضافه مجموعه.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 90, 120, 60);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/حذف مجموعه.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(60, 150, 120, 70);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/حذف مستوى.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(700, 550, 130, 60);

        jList1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 340, 230, 200);

        jTextField18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField18KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField18);
        jTextField18.setBounds(650, 180, 160, 30);

        jTextField19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jTextField19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField19KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField19);
        jTextField19.setBounds(650, 230, 160, 30);

        jTextField20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jTextField20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField20KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField20);
        jTextField20.setBounds(650, 120, 160, 30);

        jList2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(650, 340, 230, 190);

        jTextField21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField21);
        jTextField21.setBounds(240, 160, 160, 30);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/تعديل سعه مجموعه.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(20, 230, 200, 80);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/تعديل.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(620, 270, 130, 50);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/groups.jpg"))); // NOI18N
        jPanel1.add(jLabel31);
        jLabel31.setBounds(0, 0, 950, 660);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        jButton26.setBackground(new java.awt.Color(255, 255, 255));
        jButton26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton26.setContentAreaFilled(false);
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton26);
        jButton26.setBounds(40, 90, 145, 50);

        jButton22.setBackground(new java.awt.Color(255, 255, 255));
        jButton22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton22.setContentAreaFilled(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton22);
        jButton22.setBounds(40, 170, 145, 50);

        jButton23.setBackground(new java.awt.Color(255, 255, 255));
        jButton23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton23.setContentAreaFilled(false);
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton23);
        jButton23.setBounds(40, 250, 145, 50);

        jButton25.setBackground(new java.awt.Color(255, 255, 255));
        jButton25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton25.setContentAreaFilled(false);
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton25);
        jButton25.setBounds(40, 330, 145, 55);

        jButton21.setBackground(new java.awt.Color(255, 255, 255));
        jButton21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton21.setContentAreaFilled(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton21);
        jButton21.setBounds(40, 407, 145, 50);

        jButton24.setBackground(new java.awt.Color(255, 255, 255));
        jButton24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton24.setContentAreaFilled(false);
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton24);
        jButton24.setBounds(40, 490, 145, 55);

        jButton28.setBackground(new java.awt.Color(255, 255, 255));
        jButton28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton28.setContentAreaFilled(false);
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton28);
        jButton28.setBounds(40, 570, 145, 55);

        jLabel62.setBackground(new java.awt.Color(0, 102, 204));
        jLabel62.setForeground(new java.awt.Color(0, 102, 204));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/house-outline.jpg"))); // NOI18N
        jLabel62.setToolTipText("الصفحة الرئيسية");
        jLabel62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel62);
        jLabel62.setBounds(90, 10, 50, 40);

        jLabel60.setBackground(new java.awt.Color(0, 102, 204));
        jLabel60.setForeground(new java.awt.Color(0, 102, 204));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/settings.jpg"))); // NOI18N
        jLabel60.setToolTipText("الاعدادات");
        jLabel60.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel60);
        jLabel60.setBounds(10, 10, 60, 40);

        jLabel61.setBackground(new java.awt.Color(0, 102, 204));
        jLabel61.setForeground(new java.awt.Color(0, 102, 204));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/logout.jpg"))); // NOI18N
        jLabel61.setToolTipText("تسجيل الخروج");
        jLabel61.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel61MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel61);
        jLabel61.setBounds(150, 10, 60, 40);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/seee2.jpg"))); // NOI18N
        jPanel9.add(jLabel32);
        jLabel32.setBounds(0, 0, 950, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        setSize(new java.awt.Dimension(1200, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            jTextField9.enable(true);
            jTextField9.requestFocus();
        } else {
            jTextField9.enable(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if (jCheckBox3.isSelected()) {

            jTextField13.enable(true);
            jTextField13.requestFocus();
        } else {
            jTextField13.enable(false);
        }

    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if (jCheckBox2.isSelected()) {
            jTextField11.enable(true);
            jTextField11.requestFocus();

        } else {
            jTextField11.enable(false);
        }

    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        if (jCheckBox6.isSelected()) {

            jTextField16.enable(true);
            jTextField16.requestFocus();
        } else {
            jTextField16.enable(false);
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String group_name = jTextField12.getText();
        String max_num = jTextField21.getText();
        if (group_name.equals("") || max_num.equals("")) {
            JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة المجموعة", "...عذرا", 0);
            return;
        }
        if (jTextField9.getText().equals("") && jTextField11.getText().equals("") && jTextField13.getText().equals("") && jTextField14.getText().equals("") && jTextField15.getText().equals("") && jTextField16.getText().equals("") && jTextField17.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "يجب عليك اضافة وقت واحد على الاقل", "...عذرا", 0);
            return;
        }
        String name = jList2.getSelectedValue();
        jTextField20.setText(name);
        if (jTextField20.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " فقط اختر المستوى المراد اضافة المجموعة اليه من القائمة وتاكد من انك قمت باضافته من قبل", "...عذراا", 2);
            jTextField20.setText("");
            return;
        }

        int replay = JOptionPane.showConfirmDialog(this, "هل انت واثق من انك تريد اضافةالمجموعة " + group_name, "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

                String dt = getDate();
                String tm = getTime();
                ////////////////for System view ////////////
                PreparedStatement stmt2 = c.prepareStatement("insert into system values(?,?,?,?)");
                stmt2.setString(1, dt);
                stmt2.setString(2, tm);
                stmt2.setString(3, "'" + jTextField12.getText() + " __ " + jTextField20.getText() + "__" + "الحد الاقصى" + "'" + jTextField21.getText());
                stmt2.setString(4, "أضافه مجموعه");
                //    stmt2.executeUpdate();

                PreparedStatement s = c.prepareStatement("insert into groups values(?,?)");
                PreparedStatement s2 = c.prepareStatement("insert into all_groups values(?,?,?)");
                PreparedStatement s3 = c.prepareStatement("insert into groups_level values(?,?)");
                s.setString(1, group_name);
                s.setString(2, max_num);
                s.executeUpdate();
                s2.setString(1, group_name);
                if (jCheckBox1.isSelected()) {
                    s2.setString(2, "السبت");
                    s2.setString(3, jTextField9.getText());
                    s2.executeUpdate();
                }
                if (jCheckBox2.isSelected()) {
                    s2.setString(2, "الاحد");
                    s2.setString(3, jTextField11.getText());
                    s2.executeUpdate();
                }
                if (jCheckBox3.isSelected()) {
                    s2.setString(2, "الاثنين");
                    s2.setString(3, jTextField13.getText());
                    s2.executeUpdate();
                }
                if (jCheckBox4.isSelected()) {
                    s2.setString(2, "الثلاثاء");
                    s2.setString(3, jTextField14.getText());
                    s2.executeUpdate();
                }
                if (jCheckBox5.isSelected()) {
                    s2.setString(2, "الاربعاء");
                    s2.setString(3, jTextField15.getText());
                    s2.executeUpdate();
                }
                if (jCheckBox6.isSelected()) {
                    s2.setString(2, "الخميس");
                    s2.setString(3, jTextField16.getText());
                    s2.executeUpdate();
                }
                if (jCheckBox7.isSelected()) {
                    s2.setString(2, "الجمعة");
                    s2.setString(3, jTextField17.getText());
                    s2.executeUpdate();
                }

                s3.setString(1, group_name);
                s3.setString(2, name);

                s3.executeUpdate();
                jTextField20.setText("");
                dim.addElement(group_name);
                jList1.setModel(dim);

                JOptionPane.showMessageDialog(null, "تم الاضافة بنجاح", "...تم", JOptionPane.PLAIN_MESSAGE);
                stmt2.executeUpdate();

                jCheckBox1.setSelected(false);
                jCheckBox2.setSelected(false);
                jCheckBox3.setSelected(false);
                jCheckBox4.setSelected(false);
                jCheckBox5.setSelected(false);
                jCheckBox6.setSelected(false);
                jCheckBox7.setSelected(false);
                jTextField9.enable(false);
                jTextField11.enable(false);
                jTextField13.enable(false);
                jTextField14.enable(false);
                jTextField15.enable(false);
                jTextField16.enable(false);
                jTextField17.enable(false);
                jTextField12.setText("");
                jTextField21.setText("");
                jTextField9.setText("");
                jTextField11.setText("");
                jTextField13.setText("");
                jTextField14.setText("");
                jTextField15.setText("");
                jTextField16.setText("");
                jTextField17.setText("");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
                System.out.println("Error" + ex.getErrorCode());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = jList1.getSelectedValue();
        jTextField12.setText(name);
        if (jTextField12.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " فقط اختر المجموعة المراد حذفها من القائمة ", "...عذراا", 2);
            jTextField12.setText("");
            return;
        }
        int replay = JOptionPane.showConfirmDialog(this, "هل انت واثق من انك تريد حذف المجموعة احذر سوف يتم حذف اي شيئ له علاقة ", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

                String dt = getDate();
                String tm = getTime();
                ////////////////for System view ////////////
                PreparedStatement stmt8 = con.prepareStatement("insert into system values(?,?,?,?)");
                stmt8.setString(1, dt);
                stmt8.setString(2, tm);
                stmt8.setString(3, "'" + jTextField12.getText() + " __ " + jList2.getSelectedValue() + "__" + "الحد الاقصى" + "'" + jTextField21.getText());
                stmt8.setString(4, "حذف مجموعه");
                //    stmt8.executeUpdate();
                // search if there is any student in the group or not
                PreparedStatement stmt4 = con.prepareStatement("select student_id from student where student_group=?");
                stmt4.setString(1, jTextField12.getText());
                ResultSet set = stmt4.executeQuery();
                if (set.next()) {
                    JOptionPane.showMessageDialog(null, "عذرا قم بحذف كل الطلاب الموجودين بهذه المجموعة او قم بتعديل المجموعة الخاصه بهم", "عذرا", 3);
                    return;
                }
                /////////delete the group from the relation at first\\\\\\\\\\\\\\\\\\\\\\\\
                PreparedStatement stmt = con.prepareStatement("delete from all_groups where name_group=?");
                stmt.setString(1, jTextField12.getText());
                stmt.executeUpdate();
                /////////delete the group from the relation at first\\\\\\\\\\\\\\\\\\\\\\\\
                PreparedStatement stmt3 = con.prepareStatement("delete from attendence where group_name=?");
                stmt3.setString(1, jTextField12.getText());
                stmt3.executeUpdate();

                /////////delete the group from the relation at first\\\\\\\\\\\\\\\\\\\\\\\\
                PreparedStatement stmt5 = con.prepareStatement("delete from groups_level where name_group=?");
                stmt5.setString(1, jTextField12.getText());
                stmt5.executeUpdate();

                /////////////delete from the student
                /////////delete the group itself\\\\\\\\\\\\\\
                PreparedStatement stmt2 = con.prepareStatement("delete from groups where name=?");
                stmt2.setString(1, jTextField12.getText());
                stmt2.executeUpdate();

                int index = jList1.getSelectedIndex();
                dim.removeElementAt(index);
                jList1.setModel(dim);
                JOptionPane.showMessageDialog(null, "تم الحذف بنجاح", "...تم", JOptionPane.PLAIN_MESSAGE);
                stmt8.executeUpdate();
                jTextField12.setText("");

                jTextField21.setText("");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
                System.out.println("Error" + ex.getErrorCode());
            }
        } else if (replay == JOptionPane.NO_OPTION) {
            jTextField20.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String level_name = jTextField20.getText();
        String month_cost = jTextField18.getText();
        String books_cost = jTextField19.getText();

        if (level_name.equals("") || month_cost.equals("") || books_cost.equals("")) {
            JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة المستوى", "...عذرا", 0);
            return;
        }
        int replay = JOptionPane.showConfirmDialog(this, "هل انت واثق من انك تريد اضافة المستوى " + level_name, "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

                String dt = getDate();
                String tm = getTime();

                ////////////////for System view ////////////
                PreparedStatement stmt2 = c.prepareStatement("insert into system values(?,?,?,?)");
                stmt2.setString(1, dt);
                stmt2.setString(2, tm);
                stmt2.setString(3, jTextField20.getText() + " __  شهر" + " " + jTextField18.getText() + "__ مذكرات" + " " + jTextField19.getText());
                stmt2.setString(4, "أضافه فرقه");
                // stmt2.executeUpdate();

                PreparedStatement s = c.prepareStatement("insert into level values(?,?,?)");
                s.setString(1, level_name);
                s.setString(2, books_cost);
                s.setString(3, month_cost);
                s.executeUpdate();
                dim2.addElement(level_name);
                jList2.setModel(dim2);
                JOptionPane.showMessageDialog(null, "تم الاضافة بنجاح", "...تم", JOptionPane.PLAIN_MESSAGE);
                stmt2.executeUpdate();
                jTextField18.setText("");
                jTextField19.setText("");
                jTextField20.setText("");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "حدث خطا في البرنامج", "Sorry", 3);
                System.out.println("Error" + ex.getErrorCode());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name = jList2.getSelectedValue();
        jTextField20.setText(name);
        if (jTextField20.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " فقط اختر المستوى المراد حذفة من القائمة ", "...عذراا", 2);
            jTextField20.setText("");
            return;
        }
        if (!dim.isEmpty()) {
            JOptionPane.showMessageDialog(this, "يجب عليك حذف كل المجاميع المرتبطه بالمستوى قبل حذفة", "...عذراا", 2);
            return;
        }
        int replay = JOptionPane.showConfirmDialog(this, "هل انت واثق من انك تريد حذف المستوى  احذر سوف يتم حذف اي شيء له علاقة بالمستوى من طلبه و مجاميع و كل شيء ", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

                String dt = getDate();
                String tm = getTime();

                ////////////////for System view ////////////
                PreparedStatement stmt8 = con.prepareStatement("insert into system values(?,?,?,?)");
                stmt8.setString(1, dt);
                stmt8.setString(2, tm);
                stmt8.setString(3, jList2.getSelectedValue());
                stmt8.setString(4, "حذف فرقه");
                //    stmt8.executeUpdate();

                PreparedStatement stmt3 = con.prepareStatement("delete from student where student_level=?");
                stmt3.setString(1, jTextField20.getText());
                stmt3.executeUpdate();

                PreparedStatement stmt2 = con.prepareStatement("delete from groups_level where name_level=?");
                stmt2.setString(1, jTextField20.getText());
                stmt2.executeUpdate();

                PreparedStatement stmt4 = con.prepareStatement("delete from attendence where level_name =?");
                stmt4.setString(1, jTextField20.getText());
                stmt4.executeUpdate();

                PreparedStatement stmt5 = con.prepareStatement("delete from class_level where level_name =?");
                stmt5.setString(1, jTextField20.getText());
                stmt5.executeUpdate();

                PreparedStatement stmt = con.prepareStatement("delete from level where level_name=?");
                stmt.setString(1, jTextField20.getText());
                stmt.executeUpdate();

                int index = jList2.getSelectedIndex();
                dim2.removeElementAt(index);
                jList2.setModel(dim2);
                JOptionPane.showMessageDialog(null, "تم الحذف بنجاح", "...تم", JOptionPane.PLAIN_MESSAGE);
                stmt8.executeUpdate();
                jTextField18.setText("");
                jTextField19.setText("");
                jTextField20.setText("");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
                System.out.println("Error" + ex.getErrorCode());
            }
        } else if (replay == JOptionPane.NO_OPTION) {
            jTextField20.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        if (jCheckBox4.isSelected()) {

            jTextField14.enable(true);
            jTextField14.requestFocus();

        } else {
            jTextField14.enable(false);
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        if (jCheckBox5.isSelected()) {

            jTextField15.enable(true);
            jTextField15.requestFocus();

        } else {
            jTextField15.enable(false);
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        if (jCheckBox7.isSelected()) {

            jTextField17.enable(true);
            jTextField17.requestFocus();

        } else {
            jTextField17.enable(false);
        }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        String books_cost = null, month_cost = null;
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt2 = con.prepareStatement("select distinct books_cost,month_cost from level where level_name=?");
            stmt2.setString(1, jList2.getSelectedValue());
            ResultSet set2 = stmt2.executeQuery();
            while (set2.next()) {
                books_cost = set2.getString("books_cost");
                month_cost = set2.getString("month_cost");
            }
            jTextField18.setText(month_cost);
            jTextField19.setText(books_cost);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "هناك خطأ حدث", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }

        dim.clear();
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt2 = con.prepareStatement("select distinct name_group from groups_level where name_level=?");
            stmt2.setString(1, jList2.getSelectedValue());
            ResultSet set2 = stmt2.executeQuery();
            while (set2.next()) {
                String name2 = set2.getString("name_group");
                dim.addElement(name2);

            }

            jList1.setModel(dim);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "هناك خطأ حدث", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }
    }//GEN-LAST:event_jList2ValueChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String name = jList1.getSelectedValue();
        jTextField12.setText(name);

        if (jTextField12.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " فقط اختر المجموعة المراد تعديلها  من القائمة ", "...عذراا", 2);
            jTextField12.setText("");
            return;
        }
        int replay = JOptionPane.showConfirmDialog(this, "هل انت واثق من انك تريد تعديل سعة المجموعة ", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

                String dt = getDate();
                String tm = getTime();
                ////////////////for System view ////////////
                PreparedStatement stmt3 = con.prepareStatement("insert into system values(?,?,?,?)");
                stmt3.setString(1, dt);
                stmt3.setString(2, tm);
                stmt3.setString(3, "'" + jTextField12.getText() + " __ " + jList2.getSelectedValue() + "__" + "الحد الاقصى" + "'" + jTextField21.getText());
                stmt3.setString(4, "تعديل الحد الاقصى لمجموعه");
                //    stmt3.executeUpdate();

                PreparedStatement stmt2 = con.prepareStatement("update groups set max_num=? where name=?");
                stmt2.setString(1, jTextField21.getText());
                stmt2.setString(2, jTextField12.getText());
                stmt2.executeUpdate();

                JOptionPane.showMessageDialog(null, "تم التعديل بنجاح", "...تم", JOptionPane.PLAIN_MESSAGE);
                stmt3.executeUpdate();

                jTextField12.setText("");
                jTextField21.setText("");

            } catch (SQLException ex) {

                System.out.println("Error" + ex.getErrorCode());
            }
        } else if (replay == JOptionPane.NO_OPTION) {
            jTextField20.setText("");
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        try {
            String name = jList1.getSelectedValue();
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select max_num from groups where name=?");
            stmt.setString(1, name);
            ResultSet set = stmt.executeQuery();
            while (set.next()) {
                String max_num = set.getString("max_num");
                jTextField21.setText(max_num);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jList1ValueChanged

    private void jTextField20KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField18.requestFocus();
        }
    }//GEN-LAST:event_jTextField20KeyPressed

    private void jTextField18KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField19.requestFocus();
        }
    }//GEN-LAST:event_jTextField18KeyPressed

    private void jTextField19KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField19KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String level_name = jTextField20.getText();
            String month_cost = jTextField18.getText();
            String books_cost = jTextField19.getText();

            if (level_name.equals("") || month_cost.equals("") || books_cost.equals("")) {
                JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة المستوى", "...عذرا", 0);
                return;
            }
            int replay = JOptionPane.showConfirmDialog(this, "هل انت واثق من انك تريد اضافة المستوى " + level_name, "", JOptionPane.YES_NO_OPTION, 1);
            if (replay == JOptionPane.YES_OPTION) {

                try {
                    Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

                    String dt = getDate();
                    String tm = getTime();

                    ////////////////for System view ////////////
                    PreparedStatement stmt2 = c.prepareStatement("insert into system values(?,?,?,?)");
                    stmt2.setString(1, dt);
                    stmt2.setString(2, tm);
                    stmt2.setString(3, jTextField20.getText() + " __  شهر" + " " + jTextField18.getText() + "__ مذكرات" + " " + jTextField19.getText());
                    stmt2.setString(4, "أضافه فرقه");
                    // stmt2.executeUpdate();

                    PreparedStatement s = c.prepareStatement("insert into level values(?,?,?)");
                    s.setString(1, level_name);
                    s.setString(2, books_cost);
                    s.setString(3, month_cost);
                    s.executeUpdate();
                    dim2.addElement(level_name);
                    jList2.setModel(dim2);
                    JOptionPane.showMessageDialog(null, "تم الاضافة بنجاح", "...تم", JOptionPane.PLAIN_MESSAGE);
                    stmt2.executeUpdate();
                    jTextField18.setText("");
                    jTextField19.setText("");
                    jTextField20.setText("");

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "حدث خطا في البرنامج", "Sorry", 3);
                    System.out.println("Error" + ex.getErrorCode());
                }
            }
        }
    }//GEN-LAST:event_jTextField19KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String name = jList2.getSelectedValue();
        jTextField20.setText(name);
        if (jTextField20.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " فقط اختر المستوى المراد تعديله من القائمة وتاكد من انك قمت باضافته من قبل", "...عذراا", 2);
            jTextField20.setText("");
            return;
        }

        String level_name = jTextField20.getText();
        String month_cost = jTextField18.getText();
        String books_cost = jTextField19.getText();

        if (level_name.equals("") || month_cost.equals("") || books_cost.equals("")) {
            JOptionPane.showMessageDialog(null, "يجب عليك ملئ جيمع البيانات قبل اضافة المستوى", "...عذرا", 0);
            return;
        }
        int replay = JOptionPane.showConfirmDialog(this, "هل انت واثق من انك تريد تعديل المستوى " + level_name, "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

                String dt = getDate();
                String tm = getTime();

                ////////////////for System view ////////////
                PreparedStatement stmt2 = c.prepareStatement("insert into system values(?,?,?,?)");
                stmt2.setString(1, dt);
                stmt2.setString(2, tm);
                stmt2.setString(3, jTextField20.getText() + " __  شهر" + " " + jTextField18.getText() + "__ مذكرات" + " " + jTextField19.getText());
                stmt2.setString(4, "تعديل اموال فرقه");
                //    stmt2.executeUpdate();

                PreparedStatement s = c.prepareStatement("update level set month_cost=?, books_cost=?where level_name=?");
                s.setString(1, month_cost);
                s.setString(2, books_cost);
                s.setString(3, level_name);
                s.executeUpdate();
                JOptionPane.showMessageDialog(null, "تم التعديل بنجاح", "...تم", JOptionPane.PLAIN_MESSAGE);
                stmt2.executeUpdate();
                jTextField18.setText("");
                jTextField19.setText("");
                jTextField20.setText("");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "هناك خطأ حدث", "عذرا", 3);
                System.out.println("Error" + ex.getErrorCode());
            }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseClicked
        int replay = JOptionPane.showConfirmDialog(null, "هل انت متاكد من انك تريد الخروج", "تاكيد", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            LogInAs a = new LogInAs();
            this.setVisible(false);
            a.setVisible(true);
        }
    }//GEN-LAST:event_jLabel61MouseClicked

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        Settings a = new Settings();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel60MouseClicked

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        Secretary_control s = new Secretary_control();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        report a = new report();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        Groups a = new Groups();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        Money a = new Money();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        Exams a = new Exams();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        Quiz a = new Quiz();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        Attendence a = new Attendence();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        StudnetManagement a = new StudnetManagement();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField21.requestFocus();
        }

    }//GEN-LAST:event_jTextField12KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Groups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Groups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Groups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Groups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Groups().setVisible(true);
            }
        });
    }
//this function load the data of the groups in it's listbox

    private void load2() {
        jTextField9.enable(false);
        jTextField11.enable(false);
        jTextField13.enable(false);
        jTextField14.enable(false);
        jTextField15.enable(false);
        jTextField16.enable(false);
        jTextField17.enable(false);

    }

    //this function load the data of the level in it's listbox
    private void load() {

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from level");
            ResultSet set = stmt.executeQuery();
            while (set.next()) {
                String name = set.getString("level_name");
                dim2.addElement(name);
                jList2.setModel(dim2);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }
        try {
            String name = jList1.getSelectedValue();
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select max_num from groups where name=?");
            stmt.setString(1, name);
            ResultSet set = stmt.executeQuery();
            while (set.next()) {
                String max_num = set.getString("max_num");
                jTextField21.setText(max_num);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }

    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Photos/logo2.jpg")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
