package Teacher;

import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.Connection;
import login.LogInAs;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mahmoud Mansour
 */
public class MoneyManagement extends javax.swing.JFrame {

    /**
     * Creates new form MoneyManagement
     */
    public MoneyManagement() {
        initComponents();
        setIcon();
        getready();
    }

    public void getready() {
        //********** to search for levels ********
        DefaultComboBoxModel dcm2 = new DefaultComboBoxModel();
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select *from level");

            ResultSet set = stmt.executeQuery();

            dcm2.addElement("اختر");

            while (set.next()) {

                String name2 = set.getString("level_name");
                dcm2.addElement(name2);

            }

            jComboBox10.setModel(dcm2);
            jComboBox4.setModel(dcm2);
            jComboBox5.setModel(dcm2);
            

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        view_table = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jComboBox10 = new javax.swing.JComboBox<>();
        jTextField13 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        external_table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton7 = new javax.swing.JButton();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        student_exams2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        external_table1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        view_table2 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel2.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jButton19.setBackground(new java.awt.Color(255, 255, 255));
        jButton19.setContentAreaFilled(false);
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton19);
        jButton19.setBounds(40, 470, 140, 55);

        jButton20.setBackground(new java.awt.Color(255, 255, 255));
        jButton20.setContentAreaFilled(false);
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton20);
        jButton20.setBounds(40, 360, 140, 55);

        jButton21.setBackground(new java.awt.Color(255, 255, 255));
        jButton21.setContentAreaFilled(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton21);
        jButton21.setBounds(40, 145, 140, 55);

        jButton22.setBackground(new java.awt.Color(255, 255, 255));
        jButton22.setContentAreaFilled(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton22);
        jButton22.setBounds(40, 250, 140, 55);

        jLabel62.setBackground(new java.awt.Color(0, 102, 204));
        jLabel62.setForeground(new java.awt.Color(0, 102, 204));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/house-outline.jpg"))); // NOI18N
        jLabel62.setToolTipText("الصفحة الرئيسية");
        jLabel62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel62);
        jLabel62.setBounds(90, 10, 50, 40);

        jLabel60.setBackground(new java.awt.Color(0, 102, 204));
        jLabel60.setForeground(new java.awt.Color(0, 102, 204));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/settings.jpg"))); // NOI18N
        jLabel60.setToolTipText("تسجيل الخروج");
        jLabel60.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel60);
        jLabel60.setBounds(10, 10, 70, 40);

        jLabel61.setBackground(new java.awt.Color(0, 102, 204));
        jLabel61.setForeground(new java.awt.Color(0, 102, 204));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/logout.jpg"))); // NOI18N
        jLabel61.setToolTipText("تسجيل الخروج");
        jLabel61.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel61MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel61);
        jLabel61.setBounds(150, 10, 60, 40);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/SEEEE.jpg"))); // NOI18N
        jPanel8.add(jLabel32);
        jLabel32.setBounds(0, -20, 230, 700);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(970, 20, 230, 700);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اختر", "يناير", "فبراير", "مارس", "ابريل", "مايو", "يونيو", "يوليو", "اغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر" }));
        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox3MouseClicked(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(440, 120, 160, 30);

        jComboBox4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox4.setActionCommand("");
        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox4MouseClicked(evt);
            }
        });
        jPanel4.add(jComboBox4);
        jComboBox4.setBounds(70, 120, 160, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/عرض.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(330, 180, 130, 60);

        view_table.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        view_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "خصم الشهر", "خصم الملازم", "باقى الشهر", "باقى الملازم", "التاريخ", " الشهر", " الملازم", "المستوى ", "اسم الطالب"
            }
        ));
        view_table.setRowHeight(25);
        jScrollPane1.setViewportView(view_table);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(0, 260, 930, 290);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/طباعه.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(400, 570, 140, 50);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/money77.jpg"))); // NOI18N
        jPanel4.add(jLabel3);
        jLabel3.setBounds(0, 0, 930, 640);

        jTabbedPane1.addTab("عرض الدافعين ", jPanel4);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jComboBox9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اختر", "يناير", "فبراير", "مارس", "ابريل", "مايو", "يونيو", "يوليو", "اغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر" }));
        jPanel7.add(jComboBox9);
        jComboBox9.setBounds(360, 170, 160, 30);

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/بحث.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setOpaque(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11);
        jButton11.setBounds(150, 130, 110, 50);

        jTextField33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField33.setForeground(new java.awt.Color(0, 102, 153));
        jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField33.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField33.setEnabled(false);
        jPanel7.add(jTextField33);
        jTextField33.setBounds(60, 490, 160, 30);

        jTextField34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField34.setForeground(new java.awt.Color(0, 102, 153));
        jTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField34.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField34.setEnabled(false);
        jPanel7.add(jTextField34);
        jTextField34.setBounds(60, 415, 160, 30);

        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(0, 102, 153));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField11.setEnabled(false);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField11);
        jTextField11.setBounds(60, 340, 160, 30);

        jComboBox10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اختر" }));
        jComboBox10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox10MouseClicked(evt);
            }
        });
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox10);
        jComboBox10.setBounds(360, 120, 160, 30);

        jTextField13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(0, 102, 153));
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField13.setEnabled(false);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField13);
        jTextField13.setBounds(290, 340, 160, 30);

        jTextField35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField35.setForeground(new java.awt.Color(0, 102, 153));
        jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField35.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField35.setEnabled(false);
        jPanel7.add(jTextField35);
        jTextField35.setBounds(290, 415, 160, 30);

        jTextField36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField36.setForeground(new java.awt.Color(0, 102, 153));
        jTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField36.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField36.setEnabled(false);
        jPanel7.add(jTextField36);
        jTextField36.setBounds(290, 490, 160, 30);

        jTextField14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(0, 102, 153));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField14.setEnabled(false);
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField14);
        jTextField14.setBounds(535, 340, 160, 30);

        jTextField37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField37.setForeground(new java.awt.Color(0, 102, 153));
        jTextField37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField37.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField37.setEnabled(false);
        jPanel7.add(jTextField37);
        jTextField37.setBounds(535, 415, 160, 30);

        jTextField38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField38.setForeground(new java.awt.Color(0, 102, 153));
        jTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField38.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField38.setEnabled(false);
        jPanel7.add(jTextField38);
        jTextField38.setBounds(535, 490, 160, 30);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/money management.jpg"))); // NOI18N
        jPanel7.add(jLabel33);
        jLabel33.setBounds(0, 0, 950, 660);

        jTabbedPane1.addTab("عرض مصروفات الشهر للمستوى", jPanel7);

        jPanel6.setLayout(null);

        jComboBox8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اختر", "يناير", "فبراير", "مارس", "ابريل", "مايو", "يونيو", "يوليو", "اغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jComboBox8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox8KeyPressed(evt);
            }
        });
        jPanel6.add(jComboBox8);
        jComboBox8.setBounds(450, 20, 220, 40);

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/عرض.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);
        jButton10.setBounds(280, 10, 130, 60);

        jTextField29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField29.setForeground(new java.awt.Color(0, 0, 153));
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField29.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField29.setEnabled(false);
        jPanel6.add(jTextField29);
        jTextField29.setBounds(110, 560, 160, 30);

        jTextField30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField30.setForeground(new java.awt.Color(0, 0, 153));
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField30.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField30.setEnabled(false);
        jPanel6.add(jTextField30);
        jTextField30.setBounds(660, 560, 160, 30);

        jTextField31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField31.setForeground(new java.awt.Color(0, 0, 153));
        jTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField31.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField31.setEnabled(false);
        jPanel6.add(jTextField31);
        jTextField31.setBounds(130, 190, 160, 30);

        jTextField32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField32.setForeground(new java.awt.Color(0, 0, 153));
        jTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField32.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField32.setEnabled(false);
        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField32);
        jTextField32.setBounds(660, 190, 150, 30);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/طباعه.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6);
        jButton6.setBounds(400, 580, 140, 50);

        external_table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        external_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "التاريخ", "المبلغ المدفوع", "سبب الدفع", "الشخص المدفوع لة"
            }
        ));
        external_table.setRequestFocusEnabled(false);
        external_table.setRowHeight(24);
        jScrollPane2.setViewportView(external_table);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(30, 280, 870, 220);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/مصروفات 2.jpg"))); // NOI18N
        jPanel6.add(jLabel5);
        jLabel5.setBounds(-6, -6, 940, 680);

        jTabbedPane1.addTab("عرض اجمالى مصروفات الشهر", jPanel6);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        jPanel9.add(jDateChooser2);
        jDateChooser2.setBounds(630, 50, 160, 30);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/عرض.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7);
        jButton7.setBounds(370, 40, 120, 60);

        jTextField39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField39.setForeground(new java.awt.Color(0, 0, 153));
        jTextField39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField39.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField39.setEnabled(false);
        jTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField39ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField39);
        jTextField39.setBounds(630, 120, 160, 30);

        jTextField40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField40.setForeground(new java.awt.Color(0, 0, 153));
        jTextField40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField40.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField40.setEnabled(false);
        jPanel9.add(jTextField40);
        jTextField40.setBounds(610, 400, 160, 30);

        jTextField41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField41.setForeground(new java.awt.Color(0, 0, 153));
        jTextField41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField41.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        jTextField41.setEnabled(false);
        jPanel9.add(jTextField41);
        jTextField41.setBounds(30, 50, 160, 30);

        student_exams2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        student_exams2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        student_exams2.setRowHeight(25);
        jScrollPane4.setViewportView(student_exams2);

        jPanel9.add(jScrollPane4);
        jScrollPane4.setBounds(0, 180, 950, 210);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("الحالي");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(180, 50, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("المصاريف الخارجة");
        jPanel9.add(jLabel8);
        jLabel8.setBounds(770, 400, 170, 30);

        external_table1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        external_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        external_table1.setRowHeight(25);
        jScrollPane5.setViewportView(external_table1);

        jPanel9.add(jScrollPane5);
        jScrollPane5.setBounds(0, 440, 950, 210);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("المصاريف الواردة");
        jPanel9.add(jLabel9);
        jLabel9.setBounds(790, 120, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("اليوم");
        jPanel9.add(jLabel10);
        jLabel10.setBounds(760, 50, 150, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/backg.jpg"))); // NOI18N
        jLabel6.setText(" ");
        jPanel9.add(jLabel6);
        jLabel6.setBounds(0, 0, 950, 680);

        jTabbedPane1.addTab("تقرير يومي ", jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(null);

        jComboBox7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اختر", "يناير", "فبراير", "مارس", "ابريل", "مايو", "يونيو", "يوليو", "اغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر" }));
        jComboBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox7MouseClicked(evt);
            }
        });
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel10.add(jComboBox7);
        jComboBox7.setBounds(430, 120, 160, 30);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/عرض.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton8);
        jButton8.setBounds(310, 180, 140, 50);

        view_table2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        view_table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "كود الطالب", "اسم الطالب", "المجموعة"
            }
        ));
        view_table2.setRowHeight(25);
        jScrollPane3.setViewportView(view_table2);

        jPanel10.add(jScrollPane3);
        jScrollPane3.setBounds(30, 260, 880, 290);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/طباعه.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton9);
        jButton9.setBounds(400, 570, 140, 50);

        jComboBox5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اختر" }));
        jComboBox5.setActionCommand("");
        jComboBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox5MouseClicked(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel10.add(jComboBox5);
        jComboBox5.setBounds(70, 120, 160, 30);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/money77.jpg"))); // NOI18N
        jPanel10.add(jLabel11);
        jLabel11.setBounds(0, 0, 940, 640);

        jTabbedPane1.addTab("المتخلفين عن الدفع", jPanel10);

        jPanel2.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 950, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1200, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        SystemView frame = new SystemView();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        MoneyManagement frame = new MoneyManagement();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        SecretaryManagement a = new SecretaryManagement();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        report_tech frame = new report_tech();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        Teacher_control s = new Teacher_control();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        setting_tech frame = new setting_tech();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jLabel60MouseClicked

    private void jLabel61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseClicked
        int replay = JOptionPane.showConfirmDialog(null, "هل انت متاكد من انك تريد الخروج", "تاكيد", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            LogInAs a = new LogInAs();
            this.setVisible(false);
            a.setVisible(true);
        }
    }//GEN-LAST:event_jLabel61MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        boolean pass = false;
        double student_count = 0;

        String check_date = "", check_level = "", date = "", level = "", level_for_total = "", cost1 = "", total_cost1 = "", total_cost2 = "", cost2 = "", rest1 = "", rest2 = "", discount1 = "", discount2 = "";
        double cost1_num = 0, cost2_num = 0, rest1_num = 0, rest2_num = 0, discount1_num = 0, discount2_num = 0, sum_cost1 = 0, sum_cost2 = 0, sum_rest1 = 0, sum_rest2 = 0, sum_discount1 = 0, sum_discount2 = 0;
        double month_cost_num = 0, avail_num = 0, rest_num = 0, total_cost1_num = 0, total_cost2_num = 0;

        check_date = jComboBox9.getSelectedItem().toString();
        check_level = jComboBox10.getSelectedItem().toString();

        //*************** to search for money ber month and rest of it **********
        if (jComboBox10.getSelectedItem().equals("اختر") || jComboBox9.getSelectedItem().toString().equals("اختر")) {
            JOptionPane.showMessageDialog(this, "  قم بتسجيل جميع المعلومات اولا(اختر اسم الشهر)", "تحذير", JOptionPane.INFORMATION_MESSAGE);
        } else {

            //********** search number of student who  added to student table in the same level ************
            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt3 = con.prepareStatement("select *from student");

                ResultSet set3 = stmt3.executeQuery();

                String check_le = "";

                while (set3.next()) {
                    check_le = set3.getString("student_level");

                    if (check_le.equals(check_level)) {
                        student_count++;
                    }

                }
            } catch (SQLException ex) {
                System.out.println("Error _student" + ex.getErrorCode());
            }

            //******** search for real money in table money***********************
            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt = con.prepareStatement("select *from money");
                ResultSet set = stmt.executeQuery();

                //so we  need cost in money table
                while (set.next()) {

                    level = set.getString("level_name");
                    date = set.getString("date");

                    if (date.equals(check_date) && level.equals(check_level)) {

                        cost1 = set.getString("books_cost");
                        cost2 = set.getString("month_cost");
                        rest1 = set.getString("rest1");
                        rest2 = set.getString("rest2");
                        discount1 = set.getString("discount1");
                        discount2 = set.getString("discount2");

                        cost1_num = Double.parseDouble(cost1);
                        cost2_num = Double.parseDouble(cost2);
                        rest1_num = Double.parseDouble(rest1);
                        rest2_num = Double.parseDouble(rest2);
                        discount1_num = Double.parseDouble(discount1);
                        discount2_num = Double.parseDouble(discount2);

                        sum_cost1 += cost1_num;
                        sum_cost2 += cost2_num;
                        sum_rest1 += rest1_num;
                        sum_rest2 += rest2_num;
                        sum_discount1 += discount1_num;
                        sum_discount2 += discount2_num;

                        //to check if there are  student paid for this date and level
                        pass = true;
                    }

                }
            } catch (SQLException ex) {
                System.out.println("Error_money" + ex.getErrorCode());
            }

            //************************* search for the cost of student'level in level table
            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt2 = con.prepareStatement("select *from level");
                ResultSet set2 = stmt2.executeQuery();

                //  search for total from level table
                while (set2.next()) {
                    level_for_total = set2.getString("level_name");

                    if (level_for_total.equals(check_level)) {
                        total_cost1 = set2.getString("books_cost");
                        total_cost2 = set2.getString("month_cost");
                        break;
                    }
                }

            } catch (SQLException ex) {

                System.out.println("Error_level " + ex.getErrorCode());
            }

            if (pass) {

                //get number from level table
                total_cost1_num = Double.parseDouble(total_cost1);
                total_cost2_num = Double.parseDouble(total_cost2);

                //*****************************************************************
                double books_cost = (total_cost1_num * student_count) - sum_discount1;
                double books_avail = sum_cost1;
                double books_rest = (books_cost - books_avail);

                jTextField13.setText(String.valueOf(books_cost));
                jTextField35.setText(String.valueOf(books_avail));
                jTextField36.setText(String.valueOf(books_rest));

                //**********************************************************
                double month_cost = (total_cost2_num * student_count) - sum_discount2;
                double month_avail = sum_cost2;
                double month_rest = (month_cost - month_avail);

                jTextField14.setText(String.valueOf(month_cost));
                jTextField37.setText(String.valueOf(month_avail));
                jTextField38.setText(String.valueOf(month_rest));

                //*******************************************************************
                month_cost_num = (total_cost1_num + total_cost2_num) * student_count - (sum_discount1 + sum_discount2);
                avail_num = sum_cost1 + sum_cost2;
                rest_num = (books_rest + month_rest);

                jTextField11.setText(String.valueOf(month_cost_num));
                jTextField34.setText(String.valueOf(avail_num));
                jTextField33.setText(String.valueOf(rest_num));

            } else {

                JOptionPane.showMessageDialog(this, "لم يتم اضافة مصروفات فى هذا الشهر لنفس المستوى", "الناتج", JOptionPane.INFORMATION_MESSAGE);

            }

        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jComboBox10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox10MouseClicked

    }//GEN-LAST:event_jComboBox10MouseClicked

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8KeyPressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        boolean pass = false;

        String check_date = "", date = "", cost1 = "", cost2 = "", rest1 = "", rest2 = "", discount1 = "", discount2 = "";
        double cost1_num = 0, cost2_num = 0, rest1_num = 0, rest2_num = 0, discount1_num = 0, discount2_num = 0, sum_cost1 = 0, sum_cost2 = 0, sum_rest1 = 0, sum_rest2 = 0, sum_discount1 = 0, sum_discount2 = 0;
        double month_cost_num = 0, avail_num = 0, rest_num = 0;

        check_date = jComboBox8.getSelectedItem().toString();

        //*************** to search for money ber month and rest of it **********
        if (jComboBox8.getSelectedItem().equals("اختر")) {
            JOptionPane.showMessageDialog(this, "  قم باختيار الشهر", "تحذير", JOptionPane.INFORMATION_MESSAGE);
        } else {

            //******** search for real money in table money***********************
            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt = con.prepareStatement("select *from money");
                ResultSet set = stmt.executeQuery();

                //so we  need cost in money table
                while (set.next()) {

                    date = set.getString("date");

                    if (date.equals(check_date)) {

                        cost1 = set.getString("books_cost");
                        cost2 = set.getString("month_cost");
                        rest1 = set.getString("rest1");
                        rest2 = set.getString("rest2");
                        discount1 = set.getString("discount1");
                        discount2 = set.getString("discount2");

                        cost1_num = Double.parseDouble(cost1);
                        cost2_num = Double.parseDouble(cost2);
                        rest1_num = Double.parseDouble(rest1);
                        rest2_num = Double.parseDouble(rest2);
                        discount1_num = Double.parseDouble(discount1);
                        discount2_num = Double.parseDouble(discount2);

                        sum_cost1 += cost1_num;
                        sum_cost2 += cost2_num;
                        sum_rest1 += rest1_num;
                        sum_rest2 += rest2_num;
                        sum_discount1 += discount1_num;
                        sum_discount2 += discount2_num;

                        //to check if there are  student paid for this date and level
                        pass = true;
                    }

                }
            } catch (SQLException ex) {
                System.out.println("Error_money" + ex.getErrorCode());
            }

            if (pass) {
                avail_num = sum_cost1 + sum_cost2;
                rest_num = sum_rest1 + sum_rest2;

                jTextField32.setText(String.valueOf(avail_num));
                jTextField31.setText(String.valueOf(rest_num));

            } else {

                JOptionPane.showMessageDialog(this, "لم يتم اضافة مصروفات فى هذا الشهر لاى مستوى المستوى", "الناتج", JOptionPane.INFORMATION_MESSAGE);

            }

            //************************************************** To show table of external money ******************************
            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt = con.prepareStatement("select *from external_money");

                ResultSet set = stmt.executeQuery();

                DefaultTableModel dm = new DefaultTableModel();

                dm.addColumn("التاريخ");
                dm.addColumn("المبلغ المدفوع");
                dm.addColumn("سبب الدفع");
                dm.addColumn("الشخص المدفوع لة");

                String money = "";
                double money_num = 0, sum_num = 0;

                while (set.next()) {

                    money = set.getString(3);
                    money_num = Double.parseDouble(money);
                    sum_num += money_num;

                    String r[] = {set.getString(4), money, set.getString(2),
                        set.getString(1)};
                    dm.addRow(r);
                }
                external_table.setModel(dm);

                //************** put the sum in its textfield **********
                jTextField30.setText(String.valueOf(sum_num));

                //****************** show the rest of avail from internal and external money *******
                //sum_num : from external
                //avail_num :from internal
                double sum_avail = avail_num - sum_num;

                jTextField29.setText(String.valueOf(sum_avail));

            } catch (SQLException ex) {
                System.out.println("Error" + ex.getErrorCode());
            }

        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String foot = " ";
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt2 = con.prepareStatement("select * from footer");
            ResultSet set2 = stmt2.executeQuery();
            while (set2.next()) {
                foot = set2.getString("footer");
            }
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

        if (!(jComboBox8.getSelectedItem().toString().equals("اختر"))) {

            MessageFormat header = new MessageFormat("جدول المصروفات الخارجية لشهر  :" + "   " + jComboBox8.getSelectedItem().toString());
            MessageFormat footer = new MessageFormat(foot);

            try {
                external_table.print(JTable.PrintMode.FIT_WIDTH, header, footer);

            } catch (PrinterException ex) {

            }

        } else {
            JOptionPane.showMessageDialog(this, "يجب اختيار الشهر  ثم العرض للطباعة", "هام", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        //the internal money
        String day = ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText();                                        // get the last date in the database
        if (!day.equals("")) {

            boolean pass = false;
            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt = con.prepareStatement("select * from money where day between cast(? as Date)and cast(? as Date)");
                stmt.setString(1, day);
                stmt.setString(2, day);
                ResultSet set = stmt.executeQuery();

                DefaultTableModel dm = new DefaultTableModel();
                dm.addColumn(" خصم الشهر");
                dm.addColumn("خصم الملازم");
                dm.addColumn("باقى الشهر");
                dm.addColumn("باقى الملازم ");
                dm.addColumn("التاريخ ");
                dm.addColumn("الشهر ");
                dm.addColumn("الملازم ");
                dm.addColumn("المستوى ");
                dm.addColumn("اسم الطالب ");

                while (set.next()) {

                    {
                        pass = true;

                        String r[] = {set.getString(10), set.getString(9), set.getString(8),
                            set.getString(7), set.getString(6) + "  " + set.getString(11), set.getString(5), set.getString(4), set.getString(3), set.getString(2)};
                        dm.addRow(r);
                    }
                }
                if (pass) {

                    student_exams2.setModel(dm);

                } else {
                    student_exams2.setModel(dm);
                }

            } catch (SQLException ex) {
                System.out.println("Error" + ex.getErrorCode());
            }
        } else {
            JOptionPane.showMessageDialog(this, "ادخل اليوم", "هام", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //the external money
        boolean pass = false;

        String check_date = "", date = "", cost1 = "", cost2 = "", rest1 = "", rest2 = "", discount1 = "", discount2 = "";
        double cost1_num = 0, cost2_num = 0, rest1_num = 0, rest2_num = 0, discount1_num = 0, discount2_num = 0, sum_cost1 = 0, sum_cost2 = 0, sum_rest1 = 0, sum_rest2 = 0, sum_discount1 = 0, sum_discount2 = 0;
        double month_cost_num = 0, avail_num = 0, rest_num = 0;

        //*************** to search for money ber month and rest of it **********
        if (day.equals("")) {
            JOptionPane.showMessageDialog(this, "  قم باختيار اليوم", "تحذير", JOptionPane.INFORMATION_MESSAGE);
        } else {

            //******** search for real money in table money***********************
            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt = con.prepareStatement("select * from money where day between cast(? as Date)and cast(? as Date) ");
                stmt.setString(1, day);
                stmt.setString(2, day);
                ResultSet set = stmt.executeQuery();

                //so we  need cost in money table
                while (set.next()) {

                    {

                        cost1 = set.getString("books_cost");
                        cost2 = set.getString("month_cost");
                        rest1 = set.getString("rest1");
                        rest2 = set.getString("rest2");
                        discount1 = set.getString("discount1");
                        discount2 = set.getString("discount2");

                        cost1_num = Double.parseDouble(cost1);
                        cost2_num = Double.parseDouble(cost2);
                        rest1_num = Double.parseDouble(rest1);
                        rest2_num = Double.parseDouble(rest2);
                        discount1_num = Double.parseDouble(discount1);
                        discount2_num = Double.parseDouble(discount2);

                        sum_cost1 += cost1_num;
                        sum_cost2 += cost2_num;
                        sum_rest1 += rest1_num;
                        sum_rest2 += rest2_num;
                        sum_discount1 += discount1_num;
                        sum_discount2 += discount2_num;

                        //to check if there are  student paid for this date and level
                        pass = true;
                    }

                }
            } catch (SQLException ex) {
                System.out.println("Error_money" + ex.getErrorCode());
            }

            if (pass) {
                avail_num = sum_cost1 + sum_cost2;
                rest_num = sum_rest1 + sum_rest2;

                jTextField39.setText(String.valueOf(avail_num));

            } else {

                JOptionPane.showMessageDialog(this, "لم يتم اضافة مصروفات فى هذا الشهر لاى مستوى المستوى", "الناتج", JOptionPane.INFORMATION_MESSAGE);

            }

            //************************************************** To show table of external money ******************************
            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt = con.prepareStatement("select *from external_money where data between cast(? as Date)and cast(? as Date) ");
                stmt.setString(1, day);
                stmt.setString(2, day);
                ResultSet set = stmt.executeQuery();

                DefaultTableModel dm = new DefaultTableModel();

                dm.addColumn("التاريخ");
                dm.addColumn("المبلغ المدفوع");
                dm.addColumn("سبب الدفع");
                dm.addColumn("الشخص المدفوع لة");

                String money = "";
                double money_num = 0, sum_num = 0;

                while (set.next()) {

                    money = set.getString(3);
                    money_num = Double.parseDouble(money);
                    sum_num += money_num;

                    String r[] = {set.getString(4), money, set.getString(2),
                        set.getString(1)};
                    dm.addRow(r);
                }
                external_table1.setModel(dm);

                //************** put the sum in its textfield **********
                jTextField40.setText(String.valueOf(sum_num));

                //****************** show the rest of avail from internal and external money *******
                //sum_num : from external
                //avail_num :from internal
                double sum_avail = avail_num - sum_num;

                jTextField41.setText(String.valueOf(sum_avail));

            } catch (SQLException ex) {
                System.out.println("Error" + ex.getErrorCode());
            }

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39ActionPerformed

    private void jComboBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseClicked
        DefaultTableModel dm = new DefaultTableModel();
        dm.addColumn(" خصم الشهر");
        dm.addColumn("خصم الملازم");
        dm.addColumn("باقى الشهر");
        dm.addColumn("باقى الملازم ");
        dm.addColumn("التاريخ ");
        dm.addColumn("الشهر ");
        dm.addColumn("الملازم ");
        dm.addColumn("المستوى ");
        dm.addColumn("اسم الطالب ");

        view_table.setModel(dm);
    }//GEN-LAST:event_jComboBox3MouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseClicked
        DefaultTableModel dm = new DefaultTableModel();
        dm.addColumn(" خصم الشهر");
        dm.addColumn("خصم الملازم");
        dm.addColumn("باقى الشهر");
        dm.addColumn("باقى الملازم ");
        dm.addColumn("التاريخ ");
        dm.addColumn("الشهر ");
        dm.addColumn("الملازم ");
        dm.addColumn("المستوى ");
        dm.addColumn("اسم الطالب ");

        view_table.setModel(dm);
    }//GEN-LAST:event_jComboBox4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String level_combo = jComboBox4.getSelectedItem().toString();
        String month_combo = jComboBox3.getSelectedItem().toString();

        if (!level_combo.equals("اختر") && !month_combo.equals("اختر")) {

            boolean pass = false;

            String level_name = jComboBox4.getSelectedItem().toString();
            String month_name = jComboBox3.getSelectedItem().toString();

            String check_month = "";
            String check_level = "";

            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt = con.prepareStatement("select * from money");

                ResultSet set = stmt.executeQuery();

                DefaultTableModel dm = new DefaultTableModel();
                dm.addColumn(" خصم الشهر");
                dm.addColumn("خصم الملازم");
                dm.addColumn("باقى الشهر");
                dm.addColumn("باقى الملازم ");
                dm.addColumn("التاريخ ");
                dm.addColumn("الشهر ");
                dm.addColumn("الملازم ");
                dm.addColumn("المستوى ");
                dm.addColumn("اسم الطالب ");

                while (set.next()) {

                    check_level = set.getString("level_name");
                    check_month = set.getString("date");

                    if (level_name.equals(check_level) && month_name.equals(check_month)) {
                        pass = true;

                        String r[] = {set.getString(10), set.getString(9), set.getString(8),
                            set.getString(7), set.getString(6) + "  " + set.getString(11), set.getString(5), set.getString(4), set.getString(3), set.getString(2)};
                        dm.addRow(r);
                    }
                }
                if (pass) {

                    view_table.setModel(dm);

                } else {
                    JOptionPane.showMessageDialog(this, "لا يوجد مصاريف مضافة فى هذا المستوى لنفس الشهر", "هام", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (SQLException ex) {
                System.out.println("Error" + ex.getErrorCode());
            }
        } else {
            JOptionPane.showMessageDialog(this, "يجب اختيار المستوى والشهر للعرض", "هام", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String foot = " ";
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt2 = con.prepareStatement("select * from footer");
            ResultSet set2 = stmt2.executeQuery();
            while (set2.next()) {
                foot = set2.getString("footer");
            }
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

        if (!(jComboBox3.getSelectedItem().toString().equals("اختر")) || !(jComboBox4.getSelectedItem().toString().equals("اختر"))) {

            MessageFormat header = new MessageFormat("جدول مصروفات المستوى الدراسى   : " + "   " + jComboBox4.getSelectedItem().toString() + "   " + "لشهر : " + jComboBox3.getSelectedItem().toString());
            MessageFormat footer = new MessageFormat(foot);

            try {
                view_table.print(JTable.PrintMode.FIT_WIDTH, header, footer);

            } catch (PrinterException ex) {
               
            }

        } else {
            JOptionPane.showMessageDialog(this, "يجب اختيار الشهر والمستوى ثم العرض", "هام", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox7MouseClicked

    }//GEN-LAST:event_jComboBox7MouseClicked

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        boolean pass = false;

        String month_name = jComboBox7.getSelectedItem().toString();
        String level_name = jComboBox5.getSelectedItem().toString();

        String student_id = "", student_name = "", check_student_id = "", check_date = "", student_level = "";

        if (!month_name.equals("اختر") && !level_name.equals("اختر")) {

            try {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                PreparedStatement stmt = con.prepareStatement("select student.student_id,student.name,student.student_group,student.student_level from  student where student_level=?");
                PreparedStatement stmt2 = con.prepareStatement("select money.student_id,money.date from money where level_name=?");

                stmt.setString(1, level_name);

                ResultSet set = stmt.executeQuery();

                DefaultTableModel dm = new DefaultTableModel();
                dm.addColumn(" كود الطالب");
                dm.addColumn("اسم الطالب ");
                dm.addColumn("المجموعة");

                stmt2.setString(1, level_name);

                while (set.next()) {

                    student_id = set.getString("student_id");
                    ResultSet set2 = stmt2.executeQuery();

                    while (set2.next()) {
                        check_student_id = set2.getString("student_id");
                        check_date = set2.getString("date");

                        if (student_id.equals(check_student_id) && check_date.equals(month_name)) {
                            pass = false;
                            break;

                        } else {
                            pass = true;
                        }

                    }

                    if (pass) {
                        String r[] = {set.getString(1), set.getString(2), set.getString(3)};
                        dm.addRow(r);
                    }
                }

                if (check_student_id.equals("")) {
                    JOptionPane.showMessageDialog(this, "لا يوجد مصاريف مضافة فى هذا الشهر لنفس المستوى لم يدفع اي شخص اي مصاريف", "هام", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                view_table2.setModel(dm);

            } catch (SQLException ex) {
                System.out.println("Error" + ex.getErrorCode());
            }
        } else {
            JOptionPane.showMessageDialog(this, "يجب اختيار الشهر و المستوى  للعرض ", "هام", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String foot = " ";
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement stmt2 = con.prepareStatement("select * from footer");
            ResultSet set2 = stmt2.executeQuery();
            while (set2.next()) {
                foot = set2.getString("footer");
            }
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

        if (!(jComboBox5.getSelectedItem().toString().equals("اختر")) || !(jComboBox7.getSelectedItem().toString().equals("اختر"))) {

           MessageFormat header = new MessageFormat("المتاخرين عن دفع شهر "+jComboBox7.getSelectedItem().toString()+"فالصف "+jComboBox5.getSelectedItem().toString());
            MessageFormat footer = new MessageFormat(foot);

            try {
                view_table2.print(JTable.PrintMode.FIT_WIDTH, header, footer);

            } catch (PrinterException ex) {
                
            }

        } else {
            JOptionPane.showMessageDialog(this, "يجب اختيار الشهر والمستوى ثم العرض", "هام", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MouseClicked

    }//GEN-LAST:event_jComboBox5MouseClicked

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoneyManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoneyManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoneyManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoneyManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoneyManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable external_table;
    private javax.swing.JTable external_table1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTable student_exams2;
    private javax.swing.JTable view_table;
    private javax.swing.JTable view_table2;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Photos/logo2.jpg")));
    }
}
