/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teacher;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import login.LogInAs;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pro-Mahmoud Reda
 */
public class SecretaryManagement extends javax.swing.JFrame {

    /**
     * Creates new form SecretaryManagement
     */
    public SecretaryManagement() {
        initComponents();
        load();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton13 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField9);
        jTextField9.setBounds(530, 250, 160, 30);

        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField10);
        jTextField10.setBounds(530, 320, 160, 30);

        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField11);
        jTextField11.setBounds(530, 400, 160, 30);

        jTextField12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField12);
        jTextField12.setBounds(530, 480, 160, 30);

        jTextField13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField13KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField13);
        jTextField13.setBounds(530, 170, 160, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/اضافة.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(250, 283, 130, 60);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/add sec.jpg"))); // NOI18N
        jPanel2.add(jLabel31);
        jLabel31.setBounds(0, 0, 950, 640);

        jTabbedPane1.addTab("اضافة سكرتير", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jTextField14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField14);
        jTextField14.setBounds(520, 180, 160, 30);

        jTextField15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField15);
        jTextField15.setBounds(520, 260, 160, 30);

        jTextField16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField16);
        jTextField16.setBounds(520, 330, 160, 30);

        jTextField17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField17);
        jTextField17.setBounds(520, 410, 160, 30);

        jTextField18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField18);
        jTextField18.setBounds(520, 490, 160, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/تعديل.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(470, 550, 120, 60);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/بحث.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(330, 200, 120, 60);

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/تنظيف.png"))); // NOI18N
        jButton15.setBorder(null);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setOpaque(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton15);
        jButton15.setBounds(590, 550, 140, 60);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox1);
        jCheckBox1.setBounds(920, 250, 80, 30);

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox2.setOpaque(false);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox2);
        jCheckBox2.setBounds(920, 170, 80, 30);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/modify sec.jpg"))); // NOI18N
        jPanel4.add(jLabel32);
        jLabel32.setBounds(0, 0, 950, 660);

        jTabbedPane1.addTab("تعديل سكرتير", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jTextField19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField19);
        jTextField19.setBounds(540, 200, 160, 30);

        jTextField20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField20);
        jTextField20.setBounds(540, 280, 160, 30);

        jTextField21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField21);
        jTextField21.setBounds(540, 355, 160, 30);

        jTextField22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField22);
        jTextField22.setBounds(540, 430, 160, 30);

        jTextField23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField23);
        jTextField23.setBounds(540, 510, 160, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/حذف1.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(490, 560, 130, 60);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/بحث.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(350, 220, 130, 60);

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/تنظيف.png"))); // NOI18N
        jButton16.setBorder(null);
        jButton16.setContentAreaFilled(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton16);
        jButton16.setBounds(620, 560, 140, 60);

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox3.setOpaque(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox3);
        jCheckBox3.setBounds(920, 270, 80, 30);

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox4.setOpaque(false);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox4);
        jCheckBox4.setBounds(920, 190, 80, 30);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/delete sec.jpg"))); // NOI18N
        jPanel5.add(jLabel33);
        jLabel33.setBounds(0, 0, 950, 700);

        jTabbedPane1.addTab("حذف سكرتير", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jTextField24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField24);
        jTextField24.setBounds(510, 170, 160, 30);

        jTextField25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField25);
        jTextField25.setBounds(510, 250, 160, 30);

        jTextField26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField26);
        jTextField26.setBounds(510, 325, 160, 30);

        jTextField27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField27);
        jTextField27.setBounds(510, 400, 160, 30);

        jTextField28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField28);
        jTextField28.setBounds(510, 480, 160, 30);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/بحث.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(300, 190, 120, 60);

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/تنظيف.png"))); // NOI18N
        jButton17.setBorder(null);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.setOpaque(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton17);
        jButton17.setBounds(530, 520, 120, 60);

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setContentAreaFilled(false);
        jCheckBox5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox5);
        jCheckBox5.setBounds(920, 240, 80, 30);

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setContentAreaFilled(false);
        jCheckBox6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox6);
        jCheckBox6.setBounds(920, 160, 80, 30);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/search sec.jpg"))); // NOI18N
        jPanel6.add(jLabel34);
        jLabel34.setBounds(0, 0, 950, 640);

        jTabbedPane1.addTab("بحث عن سكرتير", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "الكود", "الاسم", "كلمه المرور", "رقم الهاتف", "الراتب"
            }
        ));
        jTable1.setRequestFocusEnabled(false);
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jPanel7.add(jScrollPane1);
        jScrollPane1.setBounds(30, 170, 890, 240);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/عرض.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);
        jButton7.setBounds(440, 450, 90, 49);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/backg.jpg"))); // NOI18N
        jPanel7.add(jLabel35);
        jLabel35.setBounds(0, 0, 950, 640);

        jTabbedPane1.addTab("عرض السكرتارية", jPanel7);

        jPanel3.setLayout(null);

        jTextField29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField29.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField29FocusLost(evt);
            }
        });
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jTextField29.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField29KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField29);
        jTextField29.setBounds(470, 110, 160, 30);

        jTextField30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField30.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField30FocusLost(evt);
            }
        });
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });
        jTextField30.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField30KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField30);
        jTextField30.setBounds(470, 170, 160, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(240, 290, 510, 190);

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/حفظ.png"))); // NOI18N
        jButton13.setToolTipText("");
        jButton13.setBorder(null);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setOpaque(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13);
        jButton13.setBounds(440, 490, 120, 60);

        jButton23.setBackground(new java.awt.Color(255, 255, 255));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/حذف1.png"))); // NOI18N
        jButton23.setBorder(null);
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.setOpaque(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton23);
        jButton23.setBounds(160, 150, 150, 50);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/notes sec.jpg"))); // NOI18N
        jPanel3.add(jLabel36);
        jLabel36.setBounds(0, 0, 950, 640);

        jTabbedPane1.addTab("الملاحظات", jPanel3);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 950, 700);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jLabel60.setBackground(new java.awt.Color(0, 102, 204));
        jLabel60.setForeground(new java.awt.Color(0, 102, 204));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/settings.jpg"))); // NOI18N
        jLabel60.setToolTipText("تسجيل الخروج");
        jLabel60.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel60);
        jLabel60.setBounds(10, 10, 70, 40);

        jLabel62.setBackground(new java.awt.Color(0, 102, 204));
        jLabel62.setForeground(new java.awt.Color(0, 102, 204));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/house-outline.jpg"))); // NOI18N
        jLabel62.setToolTipText("الصفحة الرئيسية");
        jLabel62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel62);
        jLabel62.setBounds(90, 10, 50, 40);

        jLabel61.setBackground(new java.awt.Color(0, 102, 204));
        jLabel61.setForeground(new java.awt.Color(0, 102, 204));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/logout.jpg"))); // NOI18N
        jLabel61.setToolTipText("تسجيل الخروج");
        jLabel61.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel61MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel61);
        jLabel61.setBounds(150, 10, 60, 40);

        jButton21.setBackground(new java.awt.Color(255, 255, 255));
        jButton21.setContentAreaFilled(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton21);
        jButton21.setBounds(40, 145, 140, 55);

        jButton22.setBackground(new java.awt.Color(255, 255, 255));
        jButton22.setContentAreaFilled(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton22);
        jButton22.setBounds(40, 250, 140, 55);

        jButton20.setBackground(new java.awt.Color(255, 255, 255));
        jButton20.setContentAreaFilled(false);
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton20);
        jButton20.setBounds(40, 360, 140, 55);

        jButton19.setBackground(new java.awt.Color(255, 255, 255));
        jButton19.setContentAreaFilled(false);
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton19);
        jButton19.setBounds(40, 470, 140, 55);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/SEEEE.jpg"))); // NOI18N
        jPanel8.add(jLabel37);
        jLabel37.setBounds(0, -20, 230, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1200, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from secretary");

            ResultSet set = stmt.executeQuery();

            DefaultTableModel dm = new DefaultTableModel();

            dm.addColumn("الكود ");
            dm.addColumn("الاسم  ");
            dm.addColumn("كلمه المرور");
            dm.addColumn("رقم الهاتف ");
            dm.addColumn("الراتب");

            while (set.next()) {

                String r[] = {set.getString(1), set.getString(2),
                    set.getString(3), set.getString(4),
                    set.getString(5)};
                dm.addRow(r);
            }
            jTable1.setModel(dm);

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed


    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        String Name = jTextField29.getText();
        String ID = jTextField30.getText();
        String Note = jTextArea1.getText();

        try {
            // java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("insert into note_of_sec values(?,?,?)");

            if ("".equals(ID) || "".equals(Name) || "".equals(Note)) {
                JOptionPane.showMessageDialog(null, "من فضلك ادخل كل البيانات بحرص قبل الضغط على  حفظ  (:  ", "Sorry", JOptionPane.INFORMATION_MESSAGE);

            } else {

                stmt.setString(1, ID);
                stmt.setString(2, Name);
                stmt.setString(3, Note);

                stmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "تم حفظ البيانات بنجاح (; ", "Confirm", JOptionPane.INFORMATION_MESSAGE);
                jTextField29.setText("");
                jTextField30.setText("");
                jTextArea1.setText("");

            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "" + "عذرا ,هذا الكود لا ينتمى لهذا السكرتير \n" + "افحص البيانات مره اخرى "
                    + "", "Check", JOptionPane.ERROR_MESSAGE);
            System.out.println("error" + ex.getErrorCode());
        }


    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String name = jTextField13.getText();
        String ID = jTextField9.getText();
        String pass = jTextField10.getText();
        String phone = jTextField11.getText();
        String salary = jTextField12.getText();

        try {
            // java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("insert into secretary values(?,?,?,?,?)");

            if ("".equals(ID) || "".equals(name) || "".equals(pass) || "".equals(phone) || "".equals(salary)) {
                JOptionPane.showMessageDialog(null, "من فضلك ادخل كل البيانات بحرص قبل الضغط على  اضافه  (:  ", "Sorry", JOptionPane.INFORMATION_MESSAGE);

            } else {

                stmt.setString(1, ID);
                stmt.setString(2, name);
                stmt.setString(3, pass);
                stmt.setString(4, phone);
                stmt.setString(5, salary);

                stmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "تم حفظ البيانات بنجاح (; ", "Confirm", JOptionPane.INFORMATION_MESSAGE);
                jTextField13.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField11.setText("");
                jTextField12.setText("");

            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "" + "لا يمكنك اضافه هذا السكرتير\n " + "افحص هذه الارشادات:-  \n" + "لا يمكنك كتابه نفس الكود لأكثر من سكرتير , من فضلك اكتب كود اخر لهذا السكرتير  "
                    + "", "Check", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getErrorCode());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

        if (jCheckBox1.isSelected()) {
            jTextField15.setVisible(true);
        } else {
            jTextField15.setVisible(false);
        }


    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed

        if (jCheckBox2.isSelected()) {
            jTextField14.setVisible(true);
        } else {
            jTextField14.setVisible(false);
        }


    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed

        if (jCheckBox3.isSelected()) {
            jTextField20.setVisible(true);
        } else {
            jTextField20.setVisible(false);
        }


    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed

        if (jCheckBox4.isSelected()) {
            jTextField19.setVisible(true);
        } else {
            jTextField19.setVisible(false);
        }

    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed

        if (jCheckBox5.isSelected()) {
            jTextField25.setVisible(true);
        } else {
            jTextField25.setVisible(false);
        }

    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed

        if (jCheckBox6.isSelected()) {
            jTextField24.setVisible(true);
        } else {
            jTextField24.setVisible(false);
        }

    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //String Name=jTextField14.getText();
        //String ID=jTextField15.getText();
        String Bass = jTextField16.getText();
        String Phone = jTextField17.getText();
        String Salary = jTextField18.getText();

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select *from secretary");

            ResultSet set = stmt.executeQuery();

            String check_id, check_name;
            check_id = jTextField15.getText();
            check_name = jTextField14.getText();
            String id = "", name = "", pass = "", phone = "", salary = "";

            while (set.next()) {
                id = set.getString("id");
                name = set.getString("name");
                if (check_id.equals(id) || check_name.equals(name)) {

                    pass = set.getString("pass");
                    phone = set.getString("phone");
                    salary = set.getString("salary");

                    break;
                }

            }
            //check if it empty********************************
            if ("".equals(check_id) && "".equals(check_name)) {
                JOptionPane.showMessageDialog(null, "من فضلك اكتب الكود او الاسم الذى تبحث عنه اولا قبل الضغط على زر بحث:) ", "تحذير", JOptionPane.ERROR_MESSAGE);

                jTextField16.setText("");
                jTextField17.setText("");
                jTextField18.setText("");

            } else {

                if (!check_id.equals(id) && !check_id.equals("") && check_name.equals(name)) {

                    JOptionPane.showMessageDialog(null, " أسم هذاالسكرتير موجود ,ولكن ب كود غير هذا ", "CONFIRM", JOptionPane.INFORMATION_MESSAGE);

                    jTextField15.setText(id);
                    jTextField16.setText(pass);
                    jTextField17.setText(phone);
                    jTextField18.setText(salary);
                    jTextField15.enable(false);
                    jTextField15.setVisible(true);
                    jTextField14.setVisible(true);

                } else if (check_id.equals(id) && !check_name.equals(name) && !check_name.equals("")) {

                    JOptionPane.showMessageDialog(null, " كود هذا السكرتير موجود ,ولكن ب أسم غير هذا ", "CONFIRM", JOptionPane.INFORMATION_MESSAGE);

                    jTextField14.setText(name);
                    jTextField16.setText(pass);
                    jTextField17.setText(phone);
                    jTextField18.setText(salary);
                    jTextField15.enable(false);
                    jTextField14.setVisible(true);
                    jTextField15.setVisible(true);

                } else if (!check_id.equals(id) && !check_name.equals(name) && (!check_name.equals("") || !check_id.equals(""))) {

                    JOptionPane.showMessageDialog(null, "  هذا السكرتير غير موجود  ", "CONFIRM", JOptionPane.INFORMATION_MESSAGE);

                    jTextField16.setText("");
                    jTextField17.setText("");
                    jTextField18.setText("");

                    if (jCheckBox2.isSelected()) {
                        jTextField14.setVisible(true);
                    } else {
                        jTextField14.setVisible(false);
                    }

                    if (jCheckBox1.isSelected()) {
                        jTextField15.setVisible(true);
                    } else {
                        jTextField15.setVisible(false);
                    }

                } else {

                    jTextField15.setText(id);
                    jTextField14.setText(name);
                    jTextField16.setText(pass);
                    jTextField17.setText(phone);
                    jTextField18.setText(salary);
                    jTextField15.enable(false);
                    jTextField15.setVisible(true);
                    jTextField14.setVisible(true);

                }

            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        //String Name=jTextField19.getText();
        //String ID=jTextField20.getText();
        String Bass = jTextField21.getText();
        String Phone = jTextField22.getText();
        String Salary = jTextField23.getText();

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select *from secretary");

            ResultSet set = stmt.executeQuery();

            String check_id, check_name;
            check_id = jTextField20.getText();
            check_name = jTextField19.getText();
            String id = "", name = "", pass = "", phone = "", salary = "";

            while (set.next()) {
                id = set.getString("id");
                name = set.getString("name");
                if (check_id.equals(id) || check_name.equals(name)) {

                    pass = set.getString("pass");
                    phone = set.getString("phone");
                    salary = set.getString("salary");

                    break;
                }

            }
            //check if it empty********************************
            if ("".equals(check_id) && "".equals(check_name)) {
                JOptionPane.showMessageDialog(null, "من فضلك اكتب الكود او الاسم الذى تبحث عنه اولا قبل الضغط على زر بحث:) ", "تحذير", JOptionPane.ERROR_MESSAGE);

                jTextField21.setText("");
                jTextField22.setText("");
                jTextField23.setText("");

            } else {

                if (!check_id.equals(id) && !check_id.equals("") && check_name.equals(name)) {

                    JOptionPane.showMessageDialog(null, " أسم هذاالسكرتير موجود ,ولكن ب كود غير هذا ", "CONFIRM", JOptionPane.INFORMATION_MESSAGE);

                    jTextField20.setText(id);
                    jTextField21.setText(pass);
                    jTextField22.setText(phone);
                    jTextField23.setText(salary);
                    jTextField20.enable(true);
                    jTextField19.setVisible(true);
                    jTextField20.setVisible(true);

                } else if (check_id.equals(id) && !check_name.equals(name) && !check_name.equals("")) {

                    JOptionPane.showMessageDialog(null, " كود هذا السكرتير موجود ,ولكن ب أسم غير هذا ", "CONFIRM", JOptionPane.INFORMATION_MESSAGE);

                    jTextField19.setText(name);
                    jTextField21.setText(pass);
                    jTextField22.setText(phone);
                    jTextField23.setText(salary);
                    jTextField20.enable(true);
                    jTextField19.setVisible(true);
                    jTextField20.setVisible(true);

                } else if (!check_id.equals(id) && !check_name.equals(name) && (!check_name.equals("") || !check_id.equals(""))) {

                    JOptionPane.showMessageDialog(null, "  هذا السكرتير غير موجود  ", "CONFIRM", JOptionPane.INFORMATION_MESSAGE);

                    jTextField21.setText("");
                    jTextField22.setText("");
                    jTextField23.setText("");

                    if (jCheckBox4.isSelected()) {
                        jTextField19.setVisible(true);
                    } else {
                        jTextField19.setVisible(false);
                    }

                    if (jCheckBox3.isSelected()) {
                        jTextField20.setVisible(true);
                    } else {
                        jTextField20.setVisible(false);
                    }

                } else {

                    jTextField20.setText(id);
                    jTextField19.setText(name);
                    jTextField21.setText(pass);
                    jTextField22.setText(phone);
                    jTextField23.setText(salary);
                    jTextField20.enable(true);
                    jTextField19.setVisible(true);
                    jTextField20.setVisible(true);

                }

            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        //String Name=jTextField24.getText();
        //String ID=jTextField25.getText();
        String Bass = jTextField26.getText();
        String Phone = jTextField27.getText();
        String Salary = jTextField28.getText();

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select *from secretary");

            ResultSet set = stmt.executeQuery();

            String check_id, check_name;
            check_id = jTextField25.getText();
            check_name = jTextField24.getText();
            String id = "", name = "", pass = "", phone = "", salary = "";

            while (set.next()) {
                id = set.getString("id");
                name = set.getString("name");
                if (check_id.equals(id) || check_name.equals(name)) {

                    pass = set.getString("pass");
                    phone = set.getString("phone");
                    salary = set.getString("salary");

                    break;
                }

            }
            //check if it empty********************************
            if ("".equals(check_id) && "".equals(check_name)) {
                JOptionPane.showMessageDialog(null, "من فضلك اكتب الكود او الاسم الذى تبحث عنه اولا قبل الضغط على زر بحث:) ", "تحذير", JOptionPane.ERROR_MESSAGE);

                jTextField26.setText("");
                jTextField27.setText("");
                jTextField28.setText("");

            } else {

                if (!check_id.equals(id) && !check_id.equals("") && check_name.equals(name)) {

                    JOptionPane.showMessageDialog(null, " أسم هذاالسكرتير موجود ,ولكن ب كود غير هذا ", "CONFIRM", JOptionPane.INFORMATION_MESSAGE);

                    jTextField25.setText(id);
                    jTextField26.setText(pass);
                    jTextField27.setText(phone);
                    jTextField28.setText(salary);
                    jTextField25.enable(true);
                    jTextField24.setVisible(true);
                    jTextField25.setVisible(true);

                } else if (check_id.equals(id) && !check_name.equals(name) && !check_name.equals("")) {

                    JOptionPane.showMessageDialog(null, " كود هذا السكرتير موجود ,ولكن ب أسم غير هذا ", "CONFIRM", JOptionPane.INFORMATION_MESSAGE);

                    jTextField24.setText(name);
                    jTextField26.setText(pass);
                    jTextField27.setText(phone);
                    jTextField28.setText(salary);
                    jTextField25.enable(true);
                    jTextField24.setVisible(true);
                    jTextField25.setVisible(true);

                } else if (!check_id.equals(id) && !check_name.equals(name) && (!check_name.equals("") || !check_id.equals(""))) {

                    JOptionPane.showMessageDialog(null, "  هذا السكرتير غير موجود  ", "CONFIRM", JOptionPane.INFORMATION_MESSAGE);

                    jTextField26.setText("");
                    jTextField27.setText("");
                    jTextField28.setText("");

                    if (jCheckBox6.isSelected()) {
                        jTextField24.setVisible(true);
                    } else {
                        jTextField24.setVisible(false);
                    }

                    if (jCheckBox5.isSelected()) {
                        jTextField25.setVisible(true);
                    } else {
                        jTextField25.setVisible(false);
                    }

                } else {

                    jTextField25.setText(id);
                    jTextField24.setText(name);
                    jTextField26.setText(pass);
                    jTextField27.setText(phone);
                    jTextField28.setText(salary);
                    jTextField25.enable(true);
                    jTextField25.setVisible(true);
                    jTextField24.setVisible(true);
                }

            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        jTextField19.setText("");
        jTextField20.setText("");
        jTextField21.setText("");
        jTextField22.setText("");
        jTextField23.setText("");

        if (jCheckBox4.isSelected()) {
            jTextField19.setVisible(true);
        } else {
            jTextField19.setVisible(false);
        }

        if (jCheckBox3.isSelected()) {
            jTextField20.setVisible(true);
        } else {
            jTextField20.setVisible(false);
        }


    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField15.enable(true);
        if (jCheckBox2.isSelected()) {
            jTextField14.setVisible(true);
        } else {
            jTextField14.setVisible(false);
        }

        if (jCheckBox1.isSelected()) {
            jTextField15.setVisible(true);
        } else {
            jTextField15.setVisible(false);
        }


    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String Name = jTextField14.getText();
        String ID = jTextField15.getText();
        String Bass = jTextField16.getText();
        String Phone = jTextField17.getText();
        String Salary = jTextField18.getText();

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("update  secretary set name=?,"
                    + "pass=?,phone=?,salary=? where id=?");

            //******************* to check if it search before enter update by getting data **************
            if ("".equals(Bass) || "".equals(Phone) || "".equals(Salary)) {
                JOptionPane.showMessageDialog(null, "من فضلك ابحث عن السكرتير اولا قبل الضغط على زر  تعديل", "Sorry", JOptionPane.INFORMATION_MESSAGE);
            } else {

                stmt.setString(1, Name);
                stmt.setString(2, Bass);
                stmt.setString(3, Phone);
                stmt.setString(4, Salary);
                stmt.setString(5, ID);

                stmt.executeUpdate();
                jTextField15.enable(false);

                JOptionPane.showMessageDialog(null, "تم حفظ البيانات بنجاح ", "Confirm", JOptionPane.INFORMATION_MESSAGE);
                jTextField14.setText("");
                jTextField15.setText("");
                jTextField16.setText("");
                jTextField17.setText("");
                jTextField18.setText("");
                jTextField15.enable(true);

                if (jCheckBox2.isSelected()) {
                    jTextField14.setVisible(true);
                } else {
                    jTextField14.setVisible(false);
                }

                if (jCheckBox1.isSelected()) {
                    jTextField15.setVisible(true);
                } else {
                    jTextField15.setVisible(false);
                }

            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String Name = jTextField19.getText();
        String ID = jTextField20.getText();
        String Bass = jTextField21.getText();
        String Phone = jTextField22.getText();
        String Salary = jTextField23.getText();

        // to check if it search  or not
        if ("".equals(Name) || "".equals(ID)) {
            JOptionPane.showMessageDialog(null, "من فضلك ابحث عن الاسم أو الكود قبل الضغط على زر حذف", "Sorry", JOptionPane.INFORMATION_MESSAGE);
        } else {

            int warn1 = JOptionPane.showConfirmDialog(null, "حذف هذا السكرتير سيؤدى الى حذف جميع بياناته من النظام بالكامل,هل تريد الاستمرار  ؟", "Warning", JOptionPane.YES_NO_OPTION);

            if (warn1 == JOptionPane.YES_OPTION) {

                int warn2 = JOptionPane.showConfirmDialog(null, "هل انت متأكد انك تريد حذف هذا السكرتير ؟", "Warning", JOptionPane.YES_NO_OPTION);

                if (warn2 == JOptionPane.YES_OPTION) {

                    try {
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms?autoReconnect=true&useSSL=false", "root", "root");
                        PreparedStatement stmt2 = con.prepareStatement("delete from note_of_sec where sec_id=?");
                        PreparedStatement stmt = con.prepareStatement("delete from secretary where id=?");

                        stmt2.setString(1, ID);
                        stmt.setString(1, ID);

                        stmt2.executeUpdate();
                        stmt.executeUpdate();

                        JOptionPane.showMessageDialog(null, " تم الحذف ", "Information", JOptionPane.INFORMATION_MESSAGE);

                        jTextField19.setText("");
                        jTextField20.setText("");
                        jTextField21.setText("");
                        jTextField22.setText("");
                        jTextField23.setText("");

                        if (jCheckBox4.isSelected()) {
                            jTextField19.setVisible(true);
                        } else {
                            jTextField19.setVisible(false);
                        }

                        if (jCheckBox3.isSelected()) {
                            jTextField20.setVisible(true);
                        } else {
                            jTextField20.setVisible(false);
                        }

                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, " لقد فعلت شىء خطأ أثناء اجراء العمليه", "Information", JOptionPane.INFORMATION_MESSAGE);
                        System.out.println("Error" + ex.getErrorCode());
                    }

                }
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        jTextField24.setText("");
        jTextField25.setText("");
        jTextField26.setText("");
        jTextField27.setText("");
        jTextField28.setText("");

        if (jCheckBox5.isSelected()) {
            jTextField25.setVisible(true);
        } else {
            jTextField25.setVisible(false);
        }

        if (jCheckBox6.isSelected()) {
            jTextField24.setVisible(true);
        } else {
            jTextField24.setVisible(false);
        }


    }//GEN-LAST:event_jButton17ActionPerformed

    private void jTextField29FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField29FocusLost
        String Name = jTextField29.getText();
        String ID = jTextField30.getText();

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select *from secretary");

            ResultSet set = stmt.executeQuery();

            String check_id, check_name;
            check_id = jTextField30.getText();
            check_name = jTextField29.getText();
            String id = "", name = "";

            while (set.next()) {
                //  id = set.getString("id");
                name = set.getString("name");
                if (check_name.equals(name)) {

                    id = set.getString("id");

                    break;
                }
            }
            if (!check_name.equals(name) && !check_name.equals("")) {

                JOptionPane.showMessageDialog(null, "  اسم هذا السكرتير غير موجود,من فضلك افحص البيانات مره اخرى ", "CONFIRM", JOptionPane.INFORMATION_MESSAGE);
                jTextField30.setText("");

            }
            if (check_name.equals(name)) {

                jTextField30.setText(id);

            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }


    }//GEN-LAST:event_jTextField29FocusLost

    private void jTextField30FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField30FocusLost
        String Name = jTextField29.getText();
        String ID = jTextField30.getText();

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select *from secretary");

            ResultSet set = stmt.executeQuery();

            String check_id, check_name;
            check_id = jTextField30.getText();
            check_name = jTextField29.getText();
            String id = "", name = "";

            while (set.next()) {
                //  id = set.getString("id");
                id = set.getString("id");
                if (check_id.equals(id)) {

                    name = set.getString("name");

                    break;
                }
            }
            if (check_id.equals(id)) {

                jTextField29.setText(name);

            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }


    }//GEN-LAST:event_jTextField30FocusLost

    private void jTextField13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField9.requestFocus();
        }

    }//GEN-LAST:event_jTextField13KeyPressed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField10.requestFocus();
        }

    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField11.requestFocus();
        }

    }//GEN-LAST:event_jTextField10KeyPressed

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField12.requestFocus();
        }

    }//GEN-LAST:event_jTextField11KeyPressed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField13.getText();
            String ID = jTextField9.getText();
            String pass = jTextField10.getText();
            String phone = jTextField11.getText();
            String salary = jTextField12.getText();

            try {
                // java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms?autoReconnect=true&useSSL=false", "root", "root");
                PreparedStatement stmt = con.prepareStatement("insert into secretary values(?,?,?,?,?)");

                if ("".equals(ID) || "".equals(name) || "".equals(pass) || "".equals(phone) || "".equals(salary)) {
                    JOptionPane.showMessageDialog(null, "من فضلك ادخل كل البيانات بحرص قبل الضغط على  اضافه  (:  ", "Sorry", JOptionPane.INFORMATION_MESSAGE);

                } else {

                    stmt.setString(1, ID);
                    stmt.setString(2, name);
                    stmt.setString(3, pass);
                    stmt.setString(4, phone);
                    stmt.setString(5, salary);

                    stmt.executeUpdate();

                    JOptionPane.showMessageDialog(null, "تم حفظ البيانات بنجاح (; ", "Confirm", JOptionPane.INFORMATION_MESSAGE);
                    jTextField13.setText("");
                    jTextField9.setText("");
                    jTextField10.setText("");
                    jTextField11.setText("");
                    jTextField12.setText("");

                }

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "" + "لا يمكنك اضافه هذا السكرتير\n " + "افحص هذه الارشادات:-  \n" + "لا يمكنك كتابه نفس الكود لأكثر من سكرتير , من فضلك اكتب كود اخر لهذا السكرتير  "
                        + "", "Check", JOptionPane.ERROR_MESSAGE);
                System.out.println(ex.getErrorCode());
            }

        }


    }//GEN-LAST:event_jTextField12KeyPressed

    private void jTextField29KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField29KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField30.requestFocus();
        }

    }//GEN-LAST:event_jTextField29KeyPressed

    private void jTextField30KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField30KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextArea1.requestFocus();
        }

    }//GEN-LAST:event_jTextField30KeyPressed

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        setting_tech frame = new setting_tech();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jLabel60MouseClicked

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        Teacher_control s = new Teacher_control();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jLabel61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseClicked
        int replay = JOptionPane.showConfirmDialog(null, "هل انت متاكد من انك تريد الخروج", "تاكيد", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            LogInAs a = new LogInAs();
            this.setVisible(false);
            a.setVisible(true);
        }
    }//GEN-LAST:event_jLabel61MouseClicked

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        SecretaryManagement a = new SecretaryManagement();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        report_tech frame = new report_tech();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        MoneyManagement frame = new MoneyManagement();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        SystemView frame = new SystemView();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed

        String ID = jTextField30.getText();
        if (ID.equals("")) {
            JOptionPane.showMessageDialog(null, " اكتب كود السكرتير المراد حذف الملحوظات الخاصه به", "Information", 0);
            return;
        }
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms?autoReconnect=true&useSSL=false", "root", "root");

            PreparedStatement stmt5 = con.prepareStatement("delete from note_of_sec where sec_id=?");

            //************************** to delete ******************
            stmt5.setString(1, ID);

            stmt5.executeUpdate();

            JOptionPane.showMessageDialog(null, " تم الحذف ", "Information", JOptionPane.INFORMATION_MESSAGE);

            jTextField29.setText("");
            jTextField30.setText("");
            
            
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryManagement().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Photos/logo2.jpg")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void load() {

        jTextField14.setVisible(false);
        jTextField15.setVisible(false);
        jTextField19.setVisible(false);
        jTextField20.setVisible(false);
        jTextField24.setVisible(false);
        jTextField25.setVisible(false);

    }

}
